### ISSUE TITLE
Doesn't print HTML escaped characters

### ISSUE THREAD

**Issue by jilleJr** [openupm/openupm#1112]
Just saw that the README.md renderer, so awesome it is, just lacks printing of characters escaped with HTML styled sequences.

Here's an example I found:

![image](https://user-images.githubusercontent.com/2477952/87721140-442d0d80-c7b6-11ea-9b92-b4441037f3e3.png)

(https://openupm.com/packages/jillejr.newtonsoft.json-for-unity.converters/)

Where the `&rarr;` should actually be rendered as →

**Comment by favoyang** [comment]
Thanks for reporting the bug. The bug was caused by the misconfiguration of the underlying library htmlparser2 (during markdown HTML post-processing), ended with htmlparser2 converts `&` to `&amp;` at first.

Your page has been fixed, other pages will take up to 1h to refresh.
