### ISSUE TITLE
Package is still not available

### ISSUE THREAD

**Issue by grashaar** [openupm/openupm#120]
Hi, I have added this [package](https://openupm.com/packages/com.minhdu.uiman/) 3 hours ago, but it's still not available. I don't know what have gone wrong.

**Comment by favoyang** [comment]
@grashaar Thanks for reporting the issue. The package is processed successfully, however the package detail rendering is buggy when empty “<img />" tag.

In you case, a few HTML image close tag in README is incorrect.
```
<img src="..."><img />
should be ==> 
<img src="..."></img>
```

Anyway the rendering looks okay now.
