### ISSUE TITLE
[Request] Allow sorting by "Recently Updated" of non-"Ready to Use" packages

### ISSUE THREAD

**Issue by MostHated** [openupm/openupm#1341]
Hey there,
    Absolutely love the tool. It has helped me find many great packages that I might not have otherwise known about. That said, a good few of the ones I have found have also come from the list of packages that have not yet been added to the official OpenUPM registry but that show up under the now non-"Ready to Use" list. It would be great if that list were also able to be sorted by "Recently Updated", probably based on the repos last commit time, I would expect.

Thanks,
-MH

**Comment by favoyang** [comment]
Thanks for supporting the platform. Depends on your intention, maybe you want to try the combination of ready-to-use off and sort by published date?
- Ready-to-use means at least one package release is available.
- The published date is the submission date (when the package repository is submitted to / discovered by OpenUPM)

With the combination above you can find new packages submitted to the platform, but not available to use. Is this what you want?

**Comment by MostHated** [comment]
I appreciate the reply. While the things you mentioned are helpful, when you go to the following link : https://openupm.com/packages/?active=0&sort=updatedAt

The list that is displayed is alphabetically sorted. I am assuming that this is because the "Updated" field for items that are "Pending" shows that the package has no releases yet, but I am wondering if those items could instead be sorted based on their most recent commit date/time to their respective repos until they *are* Ready to Use, at which point they could be listed by their proper Updated time? 

This way, the pending list, when sorted by "Updated" at least ends up showing more accurate results, and lets the users still see what repos have had current updates, even though they are not yet able to be used by the OpenUPM cli. 

Thanks,
-MH

**Comment by favoyang** [comment]
It makes senses for me.

**Comment by favoyang** [comment]
> --- Edit: Strange, the link I posted, I copied directly from my browser url, but for some reason it comes back a 404 if you try to go to that url directly.

Thanks for reporting the issue. Tracked as #1383

**Comment by favoyang** [comment]
Verified and closed.
