### ISSUE TITLE
The dependency packages should be in oepnupm too?

### ISSUE THREAD

**Issue by cosmos53076** [openupm/openupm#147]
My package in oepnupm adds dependency like this, but seems that oepnupm can not add them.
![image](https://user-images.githubusercontent.com/416084/78628497-d9bb2600-78c6-11ea-937e-634648aa8f13.png)

`"dependencies": 
	{
		"com.github.cosmos53076.newtonsoft.json": "https://github.com/cosmos53076/Newtonsoft.Json.git#1.0.0"
	}`

**Comment by favoyang** [comment]
Refs https://github.com/openupm/openupm-cli#add-packages

- Dependencies that existed in our registry will be added to scoped registry as well, so UPM can resolve and install dependencies correctly.
- However UPM doesn't support git, https and file protocol for package dependencies, therefor you need install them manually.

**Comment by cosmos53076** [comment]
Got it. Thanks!
