### ISSUE TITLE
Delete version when the tag is deleted

### ISSUE THREAD

**Issue by Kirbyrawr** [openupm/openupm#1500]
I needed to create other tags, however, the build of the previous version is still in openupm page, is there any way i can remove that version? Thanks.

**Comment by favoyang** [comment]
Hi @Kirbyrawr,

Could you please show me the package you mentioned?

Anyway, to delete a published version you need to create an issue to request. Here's a [section on the documentation](https://openupm.com/docs/adding-upm-package.html#handling-failed-builds) that covers this topic:

> However, build pipelines will not rebuild an already succeeded release if detecting that the git tag is removed or retagged. Because it's a bad practice for talking off or replacing an existing release for a public registry. If the intention is to fix something, the packager owner is recommended to bump the version with a new git tag. For the rare case, please create an issue for unpublishing.

That means removing tags will not affect the published version, it simply keeps in the registry. Think about published content as a constant. The rule is the same for other publish registries like NPMJS. You can not unpublish published content. You can not even publish a package entirely after a period.

But we're a little bit flexible here. You have the choice to replace a version or delete a version if request that manually. Or even take the entire package off if that works best for you.

**Comment by favoyang** [comment]
Closed with #1504.
