### ISSUE TITLE
Delete all com.kirbyrawr packages

### ISSUE THREAD

**Issue by Kirbyrawr** [openupm/openupm#1504]
Hi there i tried to use openupm but sadly it was too tedious to manage, can you please remove the packages with the scope 'com.kirbyrawr' so that way the users dont download something they dont know, thanks and apologies.

**Comment by favoyang** [comment]
Hi @Kirbyrawr,

Thanks for trying the service. I understand that manage an open-source repository with a 3rd party build service can be bumpy at the beginning to understand how it works and the limitation.

I have removed your packages and also blocked the scope for resubmitting. But what published to the registry remains to allow existing users to continue use the content. Please read the unpublish guideline at https://openupm.com/docs/modifying-upm-package.html#modifying-or-deleting-a-published-version to learn more.

I'm here to listen to what can be improved to make you happy. If you prefer a private conversation you can also reach me via e-mail (hello [at] openupm.com) or private chat on https://discord.com/invite/FnUgWEP.

I noticed that you're managing .net libraries. I can be tricky to find a good pattern to manage the version with upstream package. You can search `nuget package` at our discord room and find a conversation that starts with the user heliosphere there.
