### ISSUE TITLE
Unpublish package version

### ISSUE THREAD

**Issue by atteneder** [openupm/openupm#1519]
Please read the guideline for [unpublishing a package version](https://openupm.com/docs/modifying-upm-package.html#modifying-or-deleting-a-published-version) first.

#### What's the reason to unpublish a version?

I changed the package name from "com.atteneder.basisu" to "com.atteneder.ktx" in the past (with version 0.4.0).
Now the old versions still show up as a separate package in UPM. I don't want users to install the old version or confuse it with the recent one.

#### What's the package name?

[com.atteneder.ktx](https://openupm.com/packages/com.atteneder.ktx)

#### Which version(s) you want to unpublish?

- 0.1.0
- 0.2.0
- 0.3.0

#### Have you removed or replaced the related Git tag(s)?

yes, replace by legacy0.1.0 and so on.

**Comment by favoyang** [comment]
Thank you for reporting the issue. It has been resolved.
