### ISSUE TITLE
Feature request: checking that package names are well-scoped

### ISSUE THREAD

**Issue by favoyang** [openupm/openupm#1521]
#### Feature category

- [ ] Website: improve the way to browse or discover packages.
- [x] Pipelines: improve the way to publish or manage a package.
- [ ] Registry: improve the registry server.
- [ ] Unity Editor: improve how OpenUPM works with the Unity Editor.
- [ ] Documentation
- [ ] Others

#### What problem does this feature solve?
Checking that package names are well-scoped: (e.g. no packages that just have scope "mypackage" or "myname.mypackage").

https://github.com/openupm/openupm/issues/1510#issuecomment-715915694

#### How should this be implemented in your opinion?

- [x] Add a new CI test to cover this to reject a PR without a good scope.
- [x] Valid the package scope in the package add form.
- [x] Update documentation.
- [x] Update blocked scopes to reject published Unity packages.
- [x] Guide existing packages to update their package names. Progression: https://github.com/openupm/openupm/issues/1521#issuecomment-751472533
- [x] Guide existing packages with "com.unity" scope but not created by Unity to update their package names.
- [ ] Remove known invalid package names from tests.

#### Are you a regular backer or sponsor at [patreon.com/openupm](https://www.patreon.com/openupm)?

Yes.

#### Are you willing to work on this yourself?

Yes.

**Comment by hybridherbst** [comment]
Do you have a separate one to track for author information?

**Comment by favoyang** [comment]
> Do you have a separate one to track for author information?

#1523

**Comment by favoyang** [comment]
BTW, those are real examples already published to OpenUPM.

**Comment by hybridherbst** [comment]
Hi @favoyang,

the main reason it should be 3 components is that package names are supposed to be unique, so the notation of "domain.author.package" makes collisions much more unlikely.
One could argue that "domain" could be dropped, but I think instead of dropping if you're unsure use "com".

I would thus argue the following ones are "bad", since they break the uniqueness of a package name and kind of claim these package names as more universal as they should be (e.g. "com.gameanalytics" sounds like the one and only game analytics package, which is certainly misleading).

- com.gameanalytics
- com.linkergenerator
- com.linqtogameobject
- com.mybox
- com.unitycsprojnuget

These would be ERRORs in my opinion. Everything with a TLD in the beginning should be an error (and that counts for all the TLDs).

These ones are "kind of" ok as the first component is the author, but I would definitely discourage them:

- caneva20.config-assets
- carlos-wilkes.lean
- paps.state-machines-core
- paps.unity-updater
- d4160.game-framework

These would be WARNINGs in my opinion. I would certainly tell people that these are not ideal.

Additionally, I'd argue that some package author names should be manually checked by someone, especially "com.unity" (there are some of the Unity GitHub projects on OpenUPM submitted by other people, which is cool, but you wouldn't want someone to go rogue and re-submit things that are actually on the Unity registry). An alternative to manual checks would be to have a block list of package names on the Unity registry, or actually doing a server-side check if that particular package name exists on the registry (e.g. existance check on http://packages.unity.com/some-package-name).

We can also take a look at the dedicated importer that Unity uses for package.json on 2020+:
![image](https://user-images.githubusercontent.com/2693840/102025971-a311a580-3d9b-11eb-88a9-48c8f01957ed.png)
To note:
- they explicitly list "name" and "organization name"
- they omit the TLD but it's the first part of the "resulting" name (and I have an open bug report because it's a bug that it's missing from the UI)

**Comment by favoyang** [comment]
Hi @hybridherbst,

Thanks for sharing valuable comments again.

> I would thus argue the following ones are "bad", since they break the uniqueness of a package name and kind of claim these package names as more universal as they should be (e.g. "com.gameanalytics" sounds like the one and only game analytics package, which is certainly misleading).
> 
> * com.gameanalytics

I don't feel the "com.gameanalytics" hints it's the only game analytics package, but I understand that GameAnalytics.com is a very strong domain name in terms of marketing, at least hints a pro player here. Though it's a common case that the product (package) and the organization share the same name. It would be more consistent to always having an organization name:
- com.gameanalytics.sdk
- com.gameanalytics.core
- com.gameanalytics.gameanalytics

So I agree with you (for a different reason) that packages with "tlds.<name>" **should be updated**.

> These ones are "kind of" ok as the first component is the author, but I would definitely discourage them:
> 
> * caneva20.config-assets

I agree that the major benefit of reverse domain name notation is that a namespace can be globally unique to its registered owner: "com.something" and "net.something" are different scopes, and it's fine. Then package names without TLDs won't get such benefits, I will consider them not strictly follow the reverse domain name notation, and **should be updated**.

That means all packages existing on the OpenUPM with only one/two components will be updated at some point.

The CI and package upload form already required 3 components.

> Additionally, I'd argue that some package author names should be manually checked by someone, especially "com.unity" (there are some of the Unity GitHub projects on OpenUPM submitted by other people, which is cool, but you wouldn't want someone to go rogue and re-submit things that are actually on the Unity registry). An alternative to manual checks would be to have a block list of package names on the Unity registry, or actually doing a server-side check if that particular package name exists on the registry (e.g. existance check on http://packages.unity.com/some-package-name).

This will be implemented later. We already have the blocked scopes at https://github.com/openupm/openupm/blob/master/data/blocked-scopes.yml. Certainly, verify directly with the Unity registry on the package submission form would be better.

> We can also take a look at the dedicated importer that Unity uses for package.json on 2020+:

See https://forum.unity.com/threads/package-naming.1021792/

> I would feel doing the 2-scope approach would be safer when all packages follow the 3-scope domain.company.package approach.

Then keep the old way - specifying full package names as scopes.

**Comment by favoyang** [comment]
#### Progression to update packages that not comply with reverse domain name notation

astar
- [ ] notify package owner
- [ ] update package name or get rejected
- [ ] remove old releases from the registry

astar.action-grid
- [ ] notify package owner
- [ ] update package name or get rejected
- [ ] remove old releases from the registry

AtlasImage
- [ ] notify package owner
- [ ] update package name or get rejected
- [ ] remove old releases from the registry

autoinjector
- [ ] notify package owner
- [ ] update package name or get rejected
- [ ] remove old releases from the registry

bindingrx
- [ ] notify package owner
- [ ] update package name or get rejected
- [ ] remove old releases from the registry

caneva20.config-assets
- [ ] notify package owner
- [ ] update package name or get rejected
- [ ] remove old releases from the registry

carlos-wilkes.lean
- [ ] notify package owner
- [ ] update package name or get rejected
- [ ] remove old releases from the registry

com.gameanalytics
- [ ] notify package owner
- [ ] update package name or get rejected
- [ ] remove old releases from the registry

com.linkergenerator
- [ ] notify package owner
- [ ] update package name or get rejected
- [ ] remove old releases from the registry

com.linqtogameobject
- [ ] notify package owner
- [ ] update package name or get rejected
- [ ] remove old releases from the registry

com.mybox
- [ ] notify package owner
- [ ] update package name or get rejected
- [ ] remove old releases from the registry

com.unitycsprojnuget
- [ ] notify package owner
- [ ] update package name or get rejected
- [ ] remove old releases from the registry

d4160.constants-and-enums-generator-kit
- [ ] notify package owner
- [ ] update package name or get rejected
- [ ] remove old releases from the registry

d4160.data_persistence-helper-system
- [ ] notify package owner
- [ ] update package name or get rejected
- [ ] remove old releases from the registry

d4160.game-framework
- [ ] notify package owner
- [ ] update package name or get rejected
- [ ] remove old releases from the registry

d4160.game-framework-core
- [ ] notify package owner
- [ ] update package name or get rejected
- [ ] remove old releases from the registry

d4160.scene_management-system
- [ ] notify package owner
- [ ] update package name or get rejected
- [ ] remove old releases from the registry

d4160.ui-loading_screen-prefabs
- [ ] notify package owner
- [ ] update package name or get rejected
- [ ] remove old releases from the registry

elzach.extensions
- [ ] notify package owner
- [ ] update package name or get rejected
- [ ] remove old releases from the registry

elzach.leveleditor
- [ ] notify package owner
- [ ] update package name or get rejected
- [ ] remove old releases from the registry

entity-inspector-extension
- [ ] notify package owner
- [ ] update package name or get rejected
- [ ] remove old releases from the registry

exit-games.photon-unity-sdk
- [ ] notify package owner
- [ ] update package name or get rejected
- [ ] remove old releases from the registry

exit-games.photon-voice-2
- [ ] notify package owner
- [ ] update package name or get rejected
- [ ] remove old releases from the registry

facepunch.steamworks
- [ ] notify package owner
- [ ] update package name or get rejected
- [ ] remove old releases from the registry

kybernetik.ult-events
- [ ] notify package owner
- [ ] update package name or get rejected
- [ ] remove old releases from the registry

moonsharp
- [ ] notify package owner
- [ ] update package name or get rejected
- [ ] remove old releases from the registry

originer
- [ ] notify package owner
- [ ] update package name or get rejected
- [ ] remove old releases from the registry

paps.maybe
- [ ] notify package owner
- [ ] update package name or get rejected
- [ ] remove old releases from the registry

paps.state-machines-core
- [ ] notify package owner
- [ ] update package name or get rejected
- [ ] remove old releases from the registry

paps.unity-updater
- [ ] notify package owner
- [ ] update package name or get rejected
- [ ] remove old releases from the registry

play-fab.unity-sdk
- [ ] notify package owner
- [ ] update package name or get rejected
- [ ] remove old releases from the registry

shitake.rosetta
- [ ] notify package owner
- [ ] update package name or get rejected
- [ ] remove old releases from the registry

st.one-line
- [ ] notify package owner
- [ ] update package name or get rejected
- [ ] remove old releases from the registry

st.rect-ex
- [ ] notify package owner
- [ ] update package name or get rejected
- [ ] remove old releases from the registry

SubAssetEditor
- [ ] notify package owner
- [ ] update package name or get rejected
- [ ] remove old releases from the registry

taras-osiris.better-defines
- [ ] notify package owner
- [ ] update package name or get rejected
- [ ] remove old releases from the registry

type-inspector
- [ ] notify package owner
- [ ] update package name or get rejected
- [ ] remove old releases from the registry

uni-git
- [ ] notify package owner
- [ ] update package name or get rejected
- [ ] remove old releases from the registry

unity-xr-input-helper-system
- [ ] notify package owner
- [ ] update package name or get rejected
- [ ] remove old releases from the registry

UnityEventDrawerEx
- [ ] notify package owner
- [ ] update package name or get rejected
- [ ] remove old releases from the registry

uniunsafeio
- [ ] notify package owner
- [ ] update package name or get rejected
- [ ] remove old releases from the registry

upm-embed
- [ ] notify package owner
- [ ] update package name or get rejected
- [ ] remove old releases from the registry

usfxr
- [ ] notify package owner
- [ ] update package name or get rejected
- [ ] remove old releases from the registry

zenject
- [ ] notify package owner
- [ ] update package name or get rejected
- [ ] remove old releases from the registry

**Comment by hamish-milne** [comment]
This was a little annoying to find :/

```
An error occurred while resolving packages:
  Package com.hmilne.moontale@file:/github/workspace/moontale-unity/Packages/com.hmilne.moontale has invalid dependencies or related test packages:
    moonsharp (dependency): Package [moonsharp@2.0.0] cannot be found
```

**Comment by favoyang** [comment]
> This was a little annoying to find :/

Sorry for the pain. You can install the package manually via Git URL: https://github.com/k0dep/MoonSharp.git

Refs: https://docs.unity3d.com/Manual/upm-ui-giturl.html
