### ISSUE TITLE
Unpublish package

### ISSUE THREAD

**Issue by mraoge** [openupm/openupm#1746]
Please read the guideline for [unpublishing a package](https://openupm.com/docs/modifying-upm-package.html#unpublishing-a-package) first.

#### What's the reason to unpublish the package entirely?
This package for tests.
#### What's the package name?
new package com.fdage.arbase
#### Have you removed the package meta file and added the package name to the blocked-scopes.yml?
No

**Comment by favoyang** [comment]
Package removed.
