### ISSUE TITLE
Repo contains "Readme.md" file, but the package only has a "Readme" file (missing extension)

### ISSUE THREAD

**Issue by waldobronchart** [openupm/openupm#1756]
#### Bug category

- [ ] Website: issues related to browse or discover packages.
- [ ] Pipelines: issues related to publish or manage a package.
- [ ] Registry: issues related to the registry server.
- [ ] Unity Editor: issues related to how OpenUPM works with the Unity Editor.
- [ ] Documentation
- [x] Others

#### Steps to reproduce

`openupm add com.bunny83.simplejson`

#### What is expected?

![image](https://user-images.githubusercontent.com/464795/103246817-cb200d80-4932-11eb-8801-0dfb9e7ff8dc.png)

#### What is actually happening?

![image](https://user-images.githubusercontent.com/464795/103246803-bfcce200-4932-11eb-8170-876b1a7e8539.png)

**Comment by favoyang** [comment]
Hi @waldobronchart,

Thanks for report the issue. Please try version "2020.9.182", which fixed the issue.

**Comment by waldobronchart** [comment]
I'm confused, which version is that?

I installed this package with `openupm-cli`, which looks like the latest version is `1.14.2`
https://www.npmjs.com/package/openupm-cli

**Comment by waldobronchart** [comment]
@favoyang I'm confused, which version is that?

I installed this package with openupm-cli, which looks like the latest version is 1.14.2
https://www.npmjs.com/package/openupm-cli

**Comment by favoyang** [comment]
Sorry for the confusion. I mean I changed the latest version from `2020.9.18` to `2020.9.182`.

Please re-run the `openupm add com.bunny83.simplejson` or use the Package Manager window to update it.

**Comment by waldobronchart** [comment]
ok got it
