### ISSUE TITLE
Report - SeembaSDK

### ISSUE THREAD

**Issue by favoyang** [openupm/openupm#1772]
## Report malware or abuse

Please fill out the form to report malware or abuse in an OpenUPM package to the OpenUPM admin team.

The OpenUPM admin team will review the report and act accordingly. In cases where malware or abuse is confirmed, the package will be removed and the namespace will be blocked.

Sensitive information should be sent to admin@openupm.com, included this issue link.

Please note that this report goes to the OpenUPM admin team for triage, not the package maintainer. To report bugs or vulnerabilities in a package please contact the maintainer directly.

If the package violates the [Unity Software Additional Terms](https://unity3d.com/legal/terms-of-service/software) or [Unity Package Guiding Principles & Guidelines](https://unity3d.com/legal/terms-of-service/software/package-guidelines), please be more specific about which term(s) it breaks. To learn more about the Unity terms, please visit the [Unity forum](https://forum.unity.com/threads/updates-to-our-terms-of-service-and-new-package-guidelines.999940/) or contact Unity at terms@unity3d.com.

#### Package information

- Package name: SeembaSDK
- Package version: https://openupm.com/packages/com.seemba.unitysdk/
- Package link: 1.0.24

#### Description of vulnerability

Please include any references, screenshots, commits, or code examples that would be useful in reproducing the security issue.

https://www.seemba.com/

- [x] this package doesn't use an open-source license: `© 2020 Seemba Inc. All Rights Reserved`
- [ ] this package linked to a monetization service. Needs to investigate whether the package advertises the service within the Unity Editor UI.

**Comment by favoyang** [comment]
![image](https://user-images.githubusercontent.com/125390/103880764-89524c80-5114-11eb-867e-8f22f8bb2944.png)
![image](https://user-images.githubusercontent.com/125390/103880772-8c4d3d00-5114-11eb-9adb-d12b6a7f5ece.png)

**Comment by JacerOmri** [comment]
We will do the necessary changes (mainly change license). Is there any other potential changes we should make to be compliant?

**Comment by favoyang** [comment]
@JacerOmri thanks for updating the license quickly. You also need to
- Add the license to your GitHub project root with a file named LICENSE.md - https://docs.unity3d.com/2019.3/Documentation/Manual/CustomPackages.html
- Add an author field to the package.json https://docs.unity3d.com/2019.3/Documentation/Manual/upm-manifestPkg.html
- Bump a version and tag it.

I may add more information later. I'm currently in discussion with Unity staff for your case - a UPM package that delivers a service that incentive end-users. I will inform you when I get enough information.

**Comment by JacerOmri** [comment]
Thank you fo the headsup @favoyang, will update soon.

**Comment by JacerOmri** [comment]
@favoyang everything is done in 1.0.26

**Comment by favoyang** [comment]
@JacerOmri thanks for the update. I will update you when I collect more information from Unity (it may take quite a while).

**Comment by favoyang** [comment]
Closed due to silence from the Unity side. Please verify if the package violates the Unity Software Additional Terms or Unity Package Guiding Principles & Guidelines yourself.
