### ISSUE TITLE
Unable to resolve some packages

### ISSUE THREAD

**Issue by quabug** [openupm/openupm#1886]
## Bug report
Unity 2020.2.3f1
Unable to resolve packages:
[com.quabug.entities-bt.builder.component.yml](/openupm/openupm/blob/master/data/packages/com.quabug.entities-bt.builder.component.yml)
[com.quabug.entities-bt.builder.visual.yml](/openupm/openupm/blob/master/data/packages/com.quabug.entities-bt.builder.visual.yml)

In the meanwhile, other packages are still working:
[com.quabug.entities-bt.essential.yml](/openupm/openupm/blob/master/data/packages/com.quabug.entities-bt.essential.yml)
[com.quabug.entities-bt.debug.component-viewer.yml](/openupm/openupm/blob/master/data/packages/com.quabug.entities-bt.debug.component-viewer.yml)

#### Bug category

- [ ] Website: issues related to browse or discover packages.
- [ ] Pipelines: issues related to publish or manage a package.
- [x] Registry: issues related to the registry server.
- [ ] Unity Editor: issues related to how OpenUPM works with the Unity Editor.
- [ ] Documentation
- [ ] Others

#### Steps to reproduce
1. Create new unity project from UnityHub
2. Add package by `openupm add com.quabug.entities-bt.builder.component`
3. Open project and waiting for resolve package.

#### What is expected?
Download package and launch into Editor.

#### What is actually happening?
![image](https://user-images.githubusercontent.com/683655/107147880-5efde400-698b-11eb-8f27-a04e283788ec.png)

#### Other relevant information
`Packages/manifest.json`:
``` json
{
  "dependencies": {
    ...
    "com.quabug.entities-bt.essential": "1.0.1",
    "com.quabug.entities-bt.debug.component-viewer": "1.0.0",
    "com.quabug.entities-bt.variable.scriptable-object": "1.0.1",
    "com.quabug.entities-bt.builder.component": "1.0.1"
  },
  "scopedRegistries": [
    {
      "name": "package.openupm.com",
      "url": "https://package.openupm.com",
      "scopes": [
        "com.openupm",
        "com.quabug.entities-bt.builder.component",
        "com.quabug.entities-bt.debug.component-viewer",
        "com.quabug.entities-bt.essential",
        "com.quabug.entities-bt.variable.scriptable-object"
      ]
    }
  ]
}
```

**Comment by favoyang** [comment]
Haven't test in Unity yet. But seems these two packages work fine.
- com.quabug.entities-bt.builder.component@1.0.1
- com.quabug.entities-bt.builder.visual@???

```
openupm view com.quabug.entities-bt.builder.component

com.quabug.entities-bt.builder.component@1.0.1 | proprietary or unlicensed | versions: 16

EntitiesBT - Component Builder
Behavior Tree for Unity Entities - Component Builder

dist
.tarball: https://package.openupm.com:443/com.quabug.entities-bt.builder.component/-/com.quabug.entities-bt.builder.component-1.0.1.tgz
.shasum: 49d0395e59de10e8341c3af5b9b90005d125eb67
.integrity: sha512-uC/OHGZkwRBF7626Ll+Ji6LBCwtgiBKHNRQujvPMHlxWvrSuRfO42NxVPw1XsHNqukzy6WjPBjdSBfOR/Rw0dg==

dependencies
com.quabug.entities-bt.essential 1.0.1
com.quabug.entities-bt.variable.scriptable-object 1.0.1

latest: 1.0.1
...
```

```
openupm view com.quabug.entities-bt.builder.visual

com.quabug.entities-bt.builder.visual@0.6.1 | proprietary or unlicensed | versions: 11

EntitiesBT - Visual Builder
Behavior Tree for Unity Entities - Visual Builder

dist
.tarball: https://package.openupm.com:443/com.quabug.entities-bt.builder.visual/-/com.quabug.entities-bt.builder.visual-0.6.1.tgz
.shasum: 070671f6bac9648f95c832f35c1609def71e763c
.integrity: sha512-DXhJkf+YDSPbOqd7ktDnBJ+VfUiy3dugZoVD7giUb0TEjSIoLFGjwaTtKIVkSwZV4/5+aXRUzSzMkWPQdcLyyQ==

dependencies
com.quabug.entities-bt.essential 1.0.1
com.quabug.entities-bt.variable.scriptable-object 1.0.1
com.unity.visualscripting.entities 0.5.0-preview.1

latest: 0.6.1
...
```

Will test in Unity Editor soon.

**Comment by favoyang** [comment]
Tested in Unity Editor 2020.2.0f1. I don't have a problem importing the package via

```
openupm add com.quabug.entities-bt.builder.component
```

Are you behind a firewall? If so, you need to set up an HTTP proxy server and update the system-level HTTP_PROXY, HTTPS_PROXY environment variables to inform Unity. In case you need the proxy only to work for OpenUPM and Unity, add these domains

```
packages.unity.com       # Unity official registry
package.openupm.com      # OpenUPM registry, notice it's `package` without the letter "s"
*.digitaloceanspaces.com # CDN, currently only use openupm.sfo2.cdn.digitaloceanspaces.com
```

If you're in Mainland China, you can just use the OpenUPM CN Region (https://openupm.cn), synced with global site hourly.
- For existing projects, open the Package/manifest.json and change every "openupm.com" to "openupm.cn"
- For further projects, you can stick with CLI `openupm-cn` (install latest openupm-cli first).

If you are curious about why your firewall only blocks certain packages. OpenUPM packages are deployed to more than one CDN/Edge server. It's possible for some packages available on a non-blocked server and others been blocked in a complex network environment.

**Comment by quabug** [comment]
Thank you for checking this out.
And the problem seems gone today.
Now it could be resolved with or without VPN.
