### ISSUE TITLE
How long for a release to be available?

### ISSUE THREAD

**Issue by grashaar** [openupm/openupm#194]
Hi, I've released the version 1.0.4 for [this](https://openupm.com/packages/com.minhdu.uiman/) package several hours ago but there isn't any sign of it being available. And I just wonder if those releases are deployed automatically or manually?

**Comment by favoyang** [comment]
About 5 minutes, I will check the issue.

**Comment by favoyang** [comment]
Thanks for bringing this to my attention. It's a build pipeline bug, has been solved.
