### ISSUE TITLE
How to update package page?

### ISSUE THREAD

**Issue by grashaar** [openupm/openupm#196]
This [package](https://openupm.com/packages/com.live2d.cubism-cubismloader/) page is missing some info, I thought it could be updated by updating README.md and releasing a new version of the package. But it doesn't seem to work that way.

**Comment by favoyang** [comment]
The package detail is crawled from Github page regularly, as I remembered every 30mins. Probably you have to wait for a while.

**Comment by grashaar** [comment]
Thanks. Then do I have to release a new version everytime I want to update the README?

**Comment by favoyang** [comment]
No need.

**Comment by hww** [comment]
> The package detail is crawled from Github page regularly, as I remembered every 30mins. Probably you have to wait for a while.

I believe there is some issue with this. For instance 

github package https://github.com/hww/XiGameTool
openupm package https://openupm.com/packages/com.hww.xigametool/

Displays this readme version after cache was cleared

![Screenshot-1](https://user-images.githubusercontent.com/773541/194919286-ceebecd6-ca2c-4820-9440-e5f6604c2e42.png)

I believe I could do something wrong.

**Comment by favoyang** [comment]
@hww wrong README file path fixed in #3451
