### ISSUE TITLE
Feature request: add NuGet Registry as uplink registry

### ISSUE THREAD

**Issue by hybridherbst** [openupm/openupm#1976]
#### Feature category

- [ ] Website: improve the way to browse or discover packages.
- [X] Pipelines: improve the way to publish or manage a package.
- [X] Registry: improve the registry server.
- [X] Unity Editor: improve how OpenUPM works with the Unity Editor.
- [ ] Documentation
- [ ] Others

#### What problem does this feature solve?

Adding NuGet Registry as an uplink registry will help with dependencies. Currently, many packages on OpenUPM that have NuGet dependendencies either ship these with their package (bad, leads to collisions) or start making "utility packages" for their own stuff (also bad, leads to collisions).

The NuGet Registry takes care of packaging up these NuGet packages in a consistent, automated way, uses proper package naming, and thus seems like a good candidate to use for tracking these dependencies.

GitHub project: https://github.com/xoofx/UnityNuGet
Uplink registry: https://unitynuget-registry.azurewebsites.net

#### How should this be implemented in your opinion?

As OpenUPM builds on Verdaccio it should be easy to add an uplink registry:
https://verdaccio.org/docs/en/configuration.html#uplinks

#### Are you a regular backer or sponsor at [patreon.com/openupm](https://www.patreon.com/openupm)?
No, but contributor to the OpenUPM universe, hopefully that counts :)

#### Are you willing to work on this yourself?
I'll give it a try if there are pointers on how to start. I don't think this repo contains a config.yaml to simply add the URL (or at least I didn't find it).

**Comment by bdovaz** [comment]
I am very much looking forward to this becoming a reality.

I also think there needs to be a plan to report packages that make use of the bad practices mentioned by @hybridherbst so they can correct it.

**Comment by hybridherbst** [comment]
@bdovaz I think similar to what @favoyang has already done to report packages that don't adhere to the Unity TOS, you could just open an issue in the openupm repo & in the source repo of that package and link them - this way it's at least tracked, and then later we could figure out how to e.g. mark packages that don't have ideal dependencies on the OpenUPM page.

I think one of the great parts of OpenUPM is also that the repos are all linked - I did a number of PRs in the past to resolve such issues myself in packages I wanted to use.

**Comment by favoyang** [comment]
The experiment uplink feature is available at https://openupm.com/nuget/

**Comment by favoyang** [comment]
The uplink feature is running for 30 days without bugs reported.

Issue closed.
