### ISSUE TITLE
Invalid published time of package at category page

### ISSUE THREAD

**Issue by Leopotam** [openupm/openupm#198]
## Steps to reproduce

Open [DOTS & ECS](https://openupm.com/packages/topics/dots-and-ecs/) category page, open [LeoECS Core](https://openupm.com/packages/com.leopotam.ecs/) package page and check badge "published".

## Expected  behavior

Both badges should be same - "a month ago".

## Actual behavior

Category page - "4 months ago".
Package page - "a month ago".

**Comment by favoyang** [comment]
The category shows the package submission time, to match with the filter "recent added", which is 4 months ago for this case.

**Comment by Leopotam** [comment]
@favoyang you mean - first submission time? Why not last updated then?

**Comment by favoyang** [comment]
@Leopotam okay, let's discuss in #199 instead.
