### ISSUE TITLE
Packages not sorted at category page

### ISSUE THREAD

**Issue by Leopotam** [openupm/openupm#199]
## Steps to reproduce

Open [DOTS & ECS](https://openupm.com/packages/topics/dots-and-ecs/) category page and try to find any sorting order rules.

## Expected  behavior

Packages can be sorted:
* Alphabetically.
* Stars amount.

## Actual behavior

Looks like all packages arranged in order of addition.

**Comment by Leopotam** [comment]
Sorry, my bad, I dont understood that sorting settings by default uses "Recently added". Strange default option, but nevermind.

**Comment by favoyang** [comment]
Yep, the intention is to promote new assets.

**Comment by Leopotam** [comment]
@favoyang ok, good to know that its normal behaviour. How can I remove my assets then and re-add it later for promotion?

**Comment by favoyang** [comment]
@Leopotam, I see your intention. It was a technical limitation to use the first submission time (recent added) over the latest update time (recent update). The website is created with the static web generator approach, back to a few months ago, all website data are relying on the YAML files where the first submission time is the only time available here. For now, the website is not entirely static generated, it did fetch data from the server, eg sort by popularity (stars).

I agree with you that use update time is better than the submission time to balance both new and updated packages. Both should get promoted. So I think switching to the update time is a good move, and will satisfy your requirements?

**Comment by Leopotam** [comment]
Well, last update should be clearer as for me.

**Comment by favoyang** [comment]
@Leopotam 

The package list page has been sorted by the last update time. The update time is crawled every 30 minutes, so there will be a delay since publishing a new version to affect the list order.

The same logic applies to the "recently updated" widget on the homepage.

**Comment by favoyang** [comment]
![image](https://user-images.githubusercontent.com/125390/80121714-402a8e80-85bf-11ea-84bb-4996d283958a.png)
