### ISSUE TITLE
Unpublish package request

### ISSUE THREAD

**Issue by Zeqian-nreal** [openupm/openupm#2076]
Please read the guideline for [unpublishing a package](https://openupm.com/docs/modifying-upm-package.html#unpublishing-a-package) first.

#### What's the reason to unpublish the package entirely?
This is a test package, which contains some business privacy information, so you need to delete and republish

#### What's the package name?
com.xr.plugin.nreal

#### Have you removed the package meta file and added the package name to the blocked-scopes.yml?
no

**Comment by favoyang** [comment]
Closed by 600c9f0b61f4b6aa7e5af13f80b03b801e5f3265
