### ISSUE TITLE
Feature Request: Search results page or Search within Packages page

### ISSUE THREAD

**Issue by yoiang** [openupm/openupm#2098]
## Feature request
This request would be to allow users to choose to see a list of search results on one page, potentially by allow for pressing Enter (Submit, Return) from within the search box and directing the browser to a page with all the results listed. One can also imagine this as a filter within the Packages page.

I apologize if this has been asked for an answered already, I could not find it with the different combinations of search words I tried!

#### Feature category

- [x] Website: improve the way to browse or discover packages.
- [ ] Pipelines: improve the way to publish or manage a package.
- [ ] Registry: improve the registry server.
- [ ] Unity Editor: improve how OpenUPM works with the Unity Editor.
- [ ] Documentation
- [ ] Others

#### What problem does this feature solve?
The most common reason I come to OpenUPM is to search for a type of library, tool, etc. I am not already acquainted with, usually using a relevant keyword (I want to organize my scene hierarchy so I search 'hierarchy' or 'scene hierarchy', I want to do some object pooling so I search for 'pool', etc. etc.). 

The flow as it stands is:

1. I type these terms into the search bar
2. Results show up in the pull down style element before or after I hit Enter depending on how quickly I am typing that day
3. At some point I hit Enter expecting to see a static list of the search results and a minor description in one page I can spring back and forth from
4. Instead I realized I have to jump from the pull down element results to each package, re-searching each time I go back or switch back to the search tab if I am opening up results in a separate tab.

#### How should this be implemented in your opinion?
An additional search results page

#### Are you a regular backer or sponsor at [patreon.com/openupm](https://www.patreon.com/openupm)?
I am not

#### Are you willing to work on this yourself?
Yes

**Comment by favoyang** [comment]
Thanks for the proposal, it looks reasonable to me.

OpenUPM uses a pure client-side search solution called FlexSearch via a patched vuepress integration called vuepress-plugin-flexsearch: https://github.com/openupm/vuepress-plugin-flexsearch.

You should be able to play with the plugin and use FlexSearch API to construct a search result page.

Client-side development docs are located at: https://openupm.com/docs/dev/#website-frontend

**Comment by XeonG** [comment]
exactly this request.. current search box is bloody awful.. I can't even understand why something like this was just left like this... it's like half the implementation of a search box but instead of just providing a list you can open into each tab, everytime I try click or even middle click it closes the result preview and you have to re-search it.. how aboslutely retarded!!! vue jeez

I just want a list or results page that looks like the 'packages' grid with screenshots (which is really useful for the developers who both to make a screenshot showing something of the tool... 

not to mention you don't get a full list of results.. just a rather limited number of results..

stuck having to re enter the search and slow open each of the rather limited results.. seriosuly 

honestly so awful.. really miss unitylist.com ;(

**Comment by favoyang** [comment]
I agree, however after #4042, #32, #3453

**Comment by yoiang** [comment]
@XeonG it's great to hear you are so passionate about this change! It's important to remember that this is a passion project and free resource and it's a lot to make demands of other people's time. Even if it were a paid resource it can be difficult to not react emotionally when such emotionally critical language is used, where a neutral or even supportive, positive tone really helps encourage people to listen to how you feel! 😊

**Comment by favoyang** [comment]
To implement this feature, we will add a "Search in package list..." option at the top of the search suggestion list. When selected, this option will redirect the user to the package list page and apply a search filter based on the user's query.

This feature is part of WIP issue #4042.

**Comment by favoyang** [comment]
Fixed by #4042.
