### ISSUE TITLE
Lister view on website needs a one column option

### ISSUE THREAD

**Issue by andybak** [openupm/openupm#227]
e.g. https://openupm.com/packages/

And it should be the default. :)

And you should probably remove the two column option while you're at it. :)

Seriously - does anyone enjoy skimming long scrolling pages with two columns? You either have to skim all the way down one side and then up the other. Or you awkwardly skim left to right as you go down which gives me a headache. (and that's particularly annoying if items have variable height!)

I've never seen a multicolumn lister that wouldn't have had vastly improved UX by being a good old-fashioned single column lister.

**Comment by favoyang** [comment]
@andybak,

Again, thanks for taking care of the UX. I have replaced the masonry layout with a two-columns fixed height layout, as the first response of the issue.

**Comment by favoyang** [comment]
@andybak,

The one-column view is added, and the two-column view remains the default layout. However, the display option is persistent with the browser local storage, you only need choice once (at the right top of a lister).
