### ISSUE TITLE
Code file is missing from ZLogger 1.5.1

### ISSUE THREAD

**Issue by laicasaane** [openupm/openupm#2322]
#### Bug category

- [ ] Website: issues related to browse or discover packages.
- [x] Pipelines: issues related to publish or manage a package.
- [ ] Registry: issues related to the registry server.
- [ ] Unity Editor: issues related to how OpenUPM works with the Unity Editor.
- [ ] Documentation
- [ ] Others

#### Steps to reproduce
- Open ZLogger repo, tag 1.5.1, and observe there are `WindowsConsoleMode.cs` and `WindowsConsoleMode.cs.meta` files
https://github.com/Cysharp/ZLogger/tree/1.5.1/src/ZLogger.Unity/Assets/Scripts/ZLogger
- Add ZString and ZLogger packages to an empty Unity project
```
openupm add com.cysharp.zstring
openupm add com.cysharp.zlogger
```
- When the packages are completedly imported, there will be compilation errors, just ignore them because the required .dlls are not imported yet
- Open `Window > Package Manager` then select the ZLogger package
- Click the button `Import into Project` under the `Samples` section of ZLogger description
- Necessary .dlls will be imported
- After that, observe the Console window to see this error log
```
Library\PackageCache\com.cysharp.zlogger@1.5.1\ZLoggerLoggingBuilderExtensions.cs(63,17): error CS0103: The name 'WindowsConsoleMode' does not exist in the current context
```
- Open the package folder at `[project root]/Library/PackageCache/com.cysharp.zlogger@1.5.1`
- The `WindowsConsoleMode.cs` and `WindowsConsoleMode.cs.meta` files are missing
- Search the build pipeline log to find there are no such files
https://dev.azure.com/openupm/openupm/_build/results?view=logs&buildId=16247&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=baa7d181-d9ee-513a-8016-f44a98fd040e

#### What is expected?
- The 2 files `WindowsConsoleMode.cs` and `WindowsConsoleMode.cs.meta` should exist in the package source

#### What is actually happening?
- The 2 files `WindowsConsoleMode.cs` and `WindowsConsoleMode.cs.meta` are missing from the package

**Comment by favoyang** [comment]
A quick investigation shows that the tag has been modified:

https://github.com/Cysharp/ZLogger/commits/1.5.1/src/ZLogger.Unity/Assets/Scripts/ZLogger

https://github.com/Cysharp/ZLogger/commit/da20a54ad0ff7fda6edb65c1a756f2ecca272ffd#diff-7c5f782c770d4f479a631c9b4e723895889550c46f5b33759b25934815039454

![image](https://user-images.githubusercontent.com/125390/127942233-f768512e-0066-4f1c-b435-b836fe220181.png)

A rebuild will be executed later today.

**Comment by laicasaane** [comment]
Thanks!

**Comment by favoyang** [comment]
Hi @laicasaane,

v1.5.1 has been replaced. You need to reinstall it to apply the change.
