### ISSUE TITLE
Feature Request: Support monorepos without package branches

### ISSUE THREAD

**Issue by reeseschultz** [openupm/openupm#2331]
#### Feature category

- [ ] Website: improve the way to browse or discover packages.
- [ ] Pipelines: improve the way to publish or manage a package.
- [ ] Registry: improve the registry server.
- [ ] Unity Editor: improve how OpenUPM works with the Unity Editor.
- [ ] Documentation
- [x] Others

#### What problem does this feature solve?

The need to subtree-split packages into separate branches is error-prone (even with automation) and leads to a great deal of complexity when releasing. That said, the Unity editor has supported Git URLs including a path param like so for a while now:

```
https://github.com/reeseschultz/ReeseUnityDemos.git?path=/Packages/com.reese.nav
```

When I add a package to OpenUPM from a monorepo, ideally I could supply a string formatted like the above. Please trust me, as the maintainer of [this repo](https://github.com/reeseschultz/ReeseUnityDemos), that doing package branches totally sucks. Rather than tagging commits on package branches, they'd all go on the main branch with the new approach I'm advocating for. Since the tags should be formatted like `nav/v0.22.2` (well, mine are, anyway), there should be no conflicts between them.

OpenUPM should then be able to distribute packages with tags like so:

```
https://github.com/reeseschultz/ReeseUnityDemos.git?path=/Packages/com.some.pkg#pkg/v1.2.3
```

Note that as far as the Unity editor is concerned, the path param *must* be specified before the revision marker (#).

And be aware that I've confirmed this format works in `2021.1.*` with `https://github.com/reeseschultz/ReeseUnityDemos.git?path=/Packages/com.reese.nav#test-tag`. `test-tag` is on `master`. I don't have other tags on `master` atm. But you can see how this will work with multiple tags and packages like a dream.

I'm about to build a GitHub Action for releasing Unity projects, stand-alone packages, and monorepos, and I want it to work by tagging "release" commits on what the user will specify as the main branch. One problem, though, is I'm not sure if OpenUPM, at present, will be compatible with this approach. Personally, I think this new approach is simpler all-around, and less confusing to users both of submitted packages and OpenUPM.

My monorepo will ideally adopt the new approach via the tool I'll make, but I will retain the old tags and package branches until a migration strategy can be determined.

Another reason to move ahead with this, is, we probably don't want new monorepos doing package branches. We want to establish a more reasonable pattern. If I'm missing something, though, please let me know.

#### How should this be implemented in your opinion?

I'm not familiar with the internals of OpenUPM, but I feel I've provided more than enough explanation to justify the need, and paint the broad strokes of what's being asked here.

#### Are you a regular backer or sponsor at [patreon.com/openupm](https://www.patreon.com/openupm)?

No.

#### Are you willing to work on this yourself?

No, I'm unfamiliar with OpenUPM, and I have a lot to do. I am, however, happy to discuss further, and to help test this feature if it were to be implemented. I hope this is acceptable.

**Comment by favoyang** [comment]
OpenUPM supports monorepo without branching already. You don't need to specify the package path, the pipelines will search for a package.json file that matches a given package name. So as long as you using a good tagging prefix (like what you've been done already `nav/0.1.1`), and let the pipelines know it by setting `gitTagPrefix: nav/` ([meta file](https://github.com/openupm/openupm/blob/master/data/packages/com.reese.nav.yml)), nothing needs to be changed.

You can even don't use a prefix, but that requires a different versioning strategy to sync all monorepo packages' versions to a single version. Not everyone likes it.

And you still have to submit multiple packages one by one to OpenUPM.

**Comment by reeseschultz** [comment]
Excellent! Thanks for letting me know, @favoyang. And apologies for taking up your time. Closing this issue.
