### ISSUE TITLE
Smart Inspector unpublish v0.8.0-re

### ISSUE THREAD

**Issue by neon-age** [openupm/openupm#2333]
#### What's the reason to unpublish a version?
Wrong version name / numeration

#### What's the package name?
com.av.smart-inspector

#### Which version(s) you want to unpublish?
v0.8.0-re

#### Have you removed or replaced the related Git tag(s)?
Yes

**Comment by favoyang** [comment]
The v0.8.0-re tag (the actual version is 0.8.0) has been unpublished.
