### ISSUE TITLE
Custom protocol URLs are wrongly turned into absolute URLs

### ISSUE THREAD

**Issue by hybridherbst** [openupm/openupm#2393]
## Bug report

OpenUPM incorrectly seems to generate relative links from markdown links that have custom protocols, e.g. when you use something like
```[Install Unity 2021.1.19f1](unityhub://2021.1.19f1/5f5eb8bbdc25)```

OpenUPM turns that into a broken absolute link like 
```https://github.com/org/repo/blob/main/unityhub://2021.1.19f1/5f5eb8bbdc25```

#### Bug category

- [X] Website: issues related to browse or discover packages.
- [ ] Pipelines: issues related to publish or manage a package.
- [ ] Registry: issues related to the registry server.
- [ ] Unity Editor: issues related to how OpenUPM works with the Unity Editor.
- [ ] Documentation
- [ ] Others

#### Steps to reproduce
Include ```[Install Unity 2021.1.19f1](unityhub://2021.1.19f1/5f5eb8bbdc25)``` in a Readme.md, as in https://openupm.com/packages/com.needle.deeplink/

#### What is expected?
Link isn't changed since there's a custom protocol in it (colon character : is part of the URL)

#### What is actually happening?
Link is turned into a wrong absolute link

**Comment by favoyang** [comment]
FYI: Links in `com.needle.deeplink` have been fixed. It will take 2-3h to refresh all other README files.

**Comment by hybridherbst** [comment]
@favoyang thanks! Unfortunately only some of the links are fixed now, I think the ones with unityhub:// protocol work and the ones with kharma: don't.

You can see here where they should point:
https://raw.githubusercontent.com/needle-tools/unity-deeplink/release/1.1.0/Readme.md

**Comment by favoyang** [comment]
@hybridherbst custom protocol with only one colon has been supported.
