### ISSUE TITLE
Unpublish package version

### ISSUE THREAD

**Issue by yimengfan** [openupm/openupm#2723]
Please read the guideline for [unpublishing a package version](https://openupm.com/docs/modifying-upm-package.html#modifying-or-deleting-a-published-version) first.

#### What's the reason to unpublish a version?
Thats version has very  serious bug as  default version. So I want delete thats  and use the 2.0.8 as default version.

#### What's the package name?
com.popo.bdframework

#### Which version(s) you want to unpublish?
2.0.7beta1、2.0.7-final、2.0.8-beta1、2.0.8-beta2、2.0.8-beta3、2.0.8-beta3.5、2.0.8-beta4、2.0.8-beta4.5

#### Have you removed or replaced the related Git tag(s)?
yes.

**Comment by favoyang** [comment]
Removing versions is not a trivial request, This is treated as a one-time exception. 

The available versions after the removal.
```
[
  '2.0.7',
  '2.0.8',
  '2.0.9-preview.1',
  '2.0.9-preview.2',
  '2.0.9-preview.3',
  '2.0.9-preview.4',
  '2.0.9-preview.5',
  '2.0.9-preview.6'
]
```

`2.0.9-preview.6` was set to the latest by default. So I won't follow your request that "use the 2.0.8 as the default version."

Please also notice that deleting those versions won't clean the Unity cache located on the user's disk (if they already installed it).
