### ISSUE TITLE
The packge unable to add.

### ISSUE THREAD

**Issue by yimengfan** [openupm/openupm#2739]
![image](https://user-images.githubusercontent.com/26621257/149763636-1f8d7b75-2030-4086-9500-eb3feda82af0.png)

**Comment by favoyang** [comment]
It's maybe the temporary sync service delay by the Tonga volcano which affects the undersea fiber cable? I don't have a problem reaching that tarball from either the States or in China mainland (using openupm.cn) now.

**Comment by yimengfan** [comment]
Thanks， Today its ok.
