### ISSUE TITLE
Unpublish package version v0.0.1-alpha

### ISSUE THREAD

**Issue by attolee** [openupm/openupm#2765]
Please read the guideline for [unpublishing a package version](https://openupm.com/docs/modifying-upm-package.html#modifying-or-deleting-a-published-version) first.

#### What's the reason to unpublish a version?

The version field of the package file should be 0.0.1 instead of 1.0.0, which tagged by v0.0.1-alpha.

#### What's the package name?

cn.attolee.m4u2

#### Which version(s) you want to unpublish?

1.0.0

#### Have you removed or replaced the related Git tag(s)?

Yes, the tag v0.0.1-alpha has been deleted, and a new tag with a shorter suffix, v0.0.1-beta, has been created.

**Comment by favoyang** [comment]
Done: removed 1.0.0 release and tagged v0.0.1-beta as latest.

```
cn.attolee.m4u2@0.0.1-beta | MIT | versions: 1

M4u2
keywords: MVVM

...
latest: 0.0.1-beta

published at 2022-02-01T06:02:55.536Z

versions:
  0.0.1-beta
```
