### ISSUE TITLE
Bug: auto merge failure

### ISSUE THREAD

**Issue by favoyang** [openupm/openupm#29]
@yoshida190,

I just notice that there're two failed (and closed) PRs that should be merged automatically. I'm sorry that let you go through a painful process. I suspect the issue caused by a recent update for the our auto merge bot. I'm working on this, and will notify you of further updates.

Refs #27, #28.

**Comment by favoyang** [comment]
@yoshda190,
I have fixed the merge bot. It shall work correctly.

But I checked the your PR #28 what you submitted is a fork of dotween lib. But your fork is even with the original repository. The original repository don't have UPM support yet (please correct me if I'm wrong). I can not find the package.json in any branches and tags. I did find an issue related https://github.com/Demigiant/dotween/issues/251, but it is not solved yet.

DoTween is a popular library. I will follow the issue and try to bring it the OpenUPM when I get more time later.

**Comment by yoshida190** [comment]
@favoyang
Thank you very much.

**Comment by favoyang** [comment]
@yoshida190
I noticed that you submit a new PR https://github.com/openupm/openupm/pull/35, this time with a upm branch. While, it's not gonna work unless you create new git tags (you can tag as semver-upm, i.e. `1.2.305-upm`).
