### ISSUE TITLE
Unpublish package

### ISSUE THREAD

**Issue by danyow** [openupm/openupm#2916]
Please read the guideline for [unpublishing a package](https://openupm.com/docs/modifying-upm-package.html#unpublishing-a-package) first.

#### What's the reason to unpublish the package entirely?
the same package(com.cysharp.unitask), Now change the name to "cn.danyow.unitask.cstringfixed"
#### What's the package name?
com.cysharp.unitask.compatible
#### Have you removed the package meta file and added the package name to the blocked-scopes.yml?
yes.

**Comment by favoyang** [comment]
closed by #2915
