### ISSUE TITLE
Build Pipeline shows ``error path: package.json`` for some versions

### ISSUE THREAD

**Issue by marwie** [openupm/openupm#2945]
#### Bug category

- [x] Pipelines: see https://openupm.com/packages/com.needle.demystify/?subPage=pipelines

#### Steps to reproduce
https://openupm.com/packages/com.needle.demystify/?subPage=pipelines

#### What is expected?
Versions being published

#### What is actually happening?
Build is not running and showing ``error path package.json``

#### Other relevant information
the package was previously on OpenUPM, then we made it private and now it is public again

**Comment by favoyang** [comment]
The package name has been changed to com.needle.console? You need to change the yaml file name and the package name field inside.

https://github.com/openupm/openupm/blob/master/data/packages/com.needle.demystify.yml

**Comment by favoyang** [comment]
Seems you already submitted a new package with com.needle.console name, then you can remove the old package yaml file with a PR.

**Comment by marwie** [comment]
Thanks for the quick reply
https://github.com/openupm/openupm/pull/2949
