### ISSUE TITLE
Unpublish package com.unimob.ui

### ISSUE THREAD

**Issue by vanifatovvlad** [openupm/openupm#3018]
Please read the guideline for [unpublishing a package](https://openupm.com/docs/modifying-upm-package.html#unpublishing-a-package) first.

#### What's the reason to unpublish the package entirely?
Package uses obsolete git repository that not maintained.
Actual version is https://openupm.com/packages/com.codewriter.unimob.ui/
It would be nice to hide the [old package](https://openupm.com/packages/com.unimob.ui/) from OpenUPM

#### What's the package name?
com.unimob.ui

#### Have you removed the package meta file and added the package name to the blocked-scopes.yml?
No

**Comment by favoyang** [comment]
`com.unimob.ui` has no published releases on OpenUPM
