### ISSUE TITLE
Unpublish package version

### ISSUE THREAD

**Issue by JohnClema** [openupm/openupm#3052]
Please read the guideline for [unpublishing a package version](https://openupm.com/docs/modifying-upm-package.html#modifying-or-deleting-a-published-version) first.

#### What's the reason to unpublish a version?
Packages were published without semver originally and did not work. They were republished with semver but the old ones were not unpublished. The old ones should be unpublished so that the semver versions of the package can build.

#### What's the package name?
[com.siemens.ros-sharp](https://openupm.com/packages/com.siemens.ros-sharp)

#### Which version(s) you want to unpublish?
[See here](https://openupm.com/packages/com.siemens.ros-sharp/?subPage=pipelines)

v1.7
v1.6
v1.5
v1.4
v1.3
v1.2c
v1.2b
v1.2a
v1.2
v1.1a
v1.1
v1.0

#### Have you removed or replaced the related Git tag(s)?
No

Looping in @MartinBischoff as he has ownership of the repository

**Comment by MartinBischoff** [comment]
I just have deleted all non-semver tags.
@JohnClema can you proceed from here?

**Comment by JohnClema** [comment]
Thanks @MartinBischoff, I think so, @favoyang are you able to input on here at all? Seems the build is failing
https://dev.azure.com/openupm/openupm/_build/results?view=logs&buildId=22597&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=b24cf96b-e476-5cd6-97ae-776d6935d22f

**Comment by favoyang** [comment]
[com.siemens.ros-sharp](https://openupm.com/packages/com.siemens.ros-sharp) does not have any published version yet. So you don't need to request an unpublishing.

The pipelines show that all Git tags can not be built, because of missing a package.json with the name `com.siemens.ros-sharp`.

To fix
- update the version of https://github.com/siemens/ros-sharp/blob/master/com.siemens.ros-sharp/package.json to `1.7.1`.
- create a Git tag `1.7.1` from the main branch.
- wait for CI to finish the build.

**Comment by JohnClema** [comment]
@favoyang thanks for the fix. @MartinBischoff I just add a pull request at https://github.com/siemens/ros-sharp/pull/430 to update the version. Could you please create the git tag?

**Comment by MartinBischoff** [comment]
done

**Comment by favoyang** [comment]
Seems the Git tag points to the a wrong commit https://github.com/siemens/ros-sharp/blob/8548ed3086212d25faba574d6846bb70cd8881ca/com.siemens.ros-sharp/package.json.

**Comment by MartinBischoff** [comment]
fixed. I set the tag before merging above *facepalm*
sorry for the inconvenience.

**Comment by JohnClema** [comment]
Thank you so much @favoyang and @MartinBischoff! 

I can pull down the package now with `openupm add com.siemens.ros-sharp`. However when I inspect the package inside of the Unity Editor, I don't think that the `.dll` files are present anymore.

![screencap](https://user-images.githubusercontent.com/1367017/169993136-576690c6-5433-462c-a95f-2a5b9d8db95e.png)

**Comment by favoyang** [comment]
The issue will be closed. Please create another issue on https://github.com/siemens/ros-sharp to discuss the UPM adoption.

Please also consider testing the package locally before pushing to production. Just check out the Git repo, add the package from the disk https://docs.unity3d.com/Manual/upm-ui-local.html, and test it. It will also fix some missing `.meta` files that appear on your screenshot.
