### ISSUE TITLE
Removing Versions without git tag prefix

### ISSUE THREAD

**Issue by haitheredavid** [openupm/openupm#3171]
Please read the guideline for [unpublishing a package version](https://openupm.com/docs/modifying-upm-package.html#modifying-or-deleting-a-published-version) first.

## Unpublish version request
I'm unsure if this is the right template to use, as I don't need to unpublish any versions but instead modify the git tag prefix. If possible it would be helpful to remove any versions published without the git-tag prefix, just to keep things clean. Please let me know what works best for this workflow,.

#### What's the reason to unpublish a version?
I am using different git tags after refactoring my packages into a mono repo. Currently there are tags in three packages that I would like to remove and only use the ones with the specific git-tag prefix. I have added an ignore to my tags with #3170 but I saw in the docs that I should send a notification as well.

#### What's the package name?
the three packages are

com.speckle.core
com.speckle.objects
com.speckle.connector

#### Which version(s) you want to unpublish?
I would like to remove any versions published with the tag `upm/` or `v`, basically removing all but the ones with the prefix `com.speckle.<package name>`

#### Have you removed or replaced the related Git tag(s)?
yes.

**Comment by favoyang** [comment]
I have issued a rebuild for all these packages. It may take up to 1h to complete.

```
com.speckle.core
com.speckle.objects
com.speckle.connector
```

**Comment by favoyang** [comment]
Packages available: 
```
com.speckle.core: 1.0.0, 1.0.1
com.speckle.objects: 1.0.0, 1.0.1
com.speckle.connector: 1.0.0
```
