### ISSUE TITLE
Feature request: how many people download packages

### ISSUE THREAD

**Issue by favoyang** [openupm/openupm#32]
Show weekly/total download for a given package.

- [x] Research NPM download-counts API
- [x] Research express middleware to hook an existing API endpoint
- [x] Research verdaccio middleware to hook an existing API endpoint
- [x] Design the install-counts solution
- [x] Implement verdaccio-install-counts middleware
- [x] Prefill 1 month of data
- [x] Add install-counts chart to the package detail page
- [x] Add downloads to the package card
- [x] Sort by download on the listing page
- [x] Add monthly install-counts badge to package detail

References
- NPM package download counts specs: https://github.com/npm/registry/blob/master/docs/download-counts.md
- The [badges/shields]( https://github.com/badges/shields) service: https://github.com/badges/shields/blob/master/services/npm/npm-downloads.service.js (the endpoint URL is hardcorded😞)

Features
- API to fetch weekly, monthly, and lifetime download counts for a package
- API to fetch the last 30 days' download counts for a package
- Bar chart for the last 30 days' download counts for a package
- Package list sorted by monthly downloads

**Comment by jcs090218** [comment]
It would be great if this feature is implemented! 👍

**Comment by De-Panther** [comment]
+1 for this feature request.
Also OpenUPM is great!

**Comment by hybridherbst** [comment]
+1 from me as well!
Total/weekly would be interesting, NuGet even has per version which is usually a good indicator of stability 😄

**Comment by Cammin** [comment]
I would also like this as a feature! This would be really amazing 😃 
If it's added, I'd also be interested in some new special badges that could be provided as well on OpenUPM pages' badge section. Something similar to this:  
![Badge](https://img.shields.io/badge/Downloads-321-brightgreen)  
in this section:  
![image](https://user-images.githubusercontent.com/55564581/114780957-e883b680-9d2c-11eb-942e-f697347a88e4.png)

**Comment by f1yingbanana** [comment]
# of downloads is a key metric to demonstrate impact for organizations considering OpenUPM support. I believe this feature could potentially drive wide-scale platform adoption.

**Comment by De-Panther** [comment]
Github didn't send a notice that this is done.
So whoever follow this issue - there are stats for OpenUPM packages🎉

**Comment by favoyang** [comment]
> Github didn't send a notice that this is done.

It's not entirely done yet, something have been blocked by a major refactor of the front-end https://github.com/openupm/openupm/issues/4042. But the major part has been shipped for a while.

**Comment by favoyang** [comment]
Fixed by #4042.
