### ISSUE TITLE
Version not updating after new tag published

### ISSUE THREAD

**Issue by jakdan99** [openupm/openupm#3248]
After publishing a new tag `eventbus/0.1.6` for [Autsoft UnitySupplements Eventbus](https://openupm.com/packages/com.autsoft.unitysupplements.eventbus/?subPage=versions), it didn't appear at packages versions list.

It was publish at the same time as [Autsoft UnitySupplements Timeline](https://openupm.com/packages/com.autsoft.unitysupplements.timeline/) and [Autsoft UnitySupplements Vitamins](https://openupm.com/packages/com.autsoft.unitysupplements.vitamins/), which both got updated to the correct version.

**Comment by favoyang** [comment]
Sorry, it's a bug and has been addressed. The pipeline should catch up in 5-10 minutes.
