### ISSUE TITLE
OpenUPM Website is not working

### ISSUE THREAD

**Issue by MartonioJunior** [openupm/openupm#3278]
#### Bug category

- [X] Website: issues related to browse or discover packages.
- [ ] Pipelines: issues related to publish or manage a package.
- [ ] Registry: issues related to the registry server.
- [ ] Unity Editor: issues related to how OpenUPM works with the Unity Editor.
- [ ] Documentation
- [ ] Others

#### Steps to reproduce
1. Type in your browser "openupm.com"

#### What is expected?
The browser will show OpenUPM's website.

#### What is actually happening?
The browser is returning "ERR_CONNECTION_REFUSED"

#### Other relevant information
Recently I made a pull request to add the package I've made to the OpenUPM repository (see #3277).
After the CI bot approved the PR, I noticed the website failed to build in the workflow, which may be the reason why the website is not working.

**Comment by MartonioJunior** [comment]
The issue is now fixed (the website is back up), though I don't know if the package appears on the website.
For now, I'll close this issue and create a new one if there's an issue related to it.

**Comment by favoyang** [comment]
https://answers.netlify.com/t/netlify-not-working-again/73816/6

It's an issue with Netlify. I'm not sure whether it is fully fixed.

Meanwhile, the failed GitHub action is being re-executing. https://github.com/openupm/openupm/actions/runs/2965825263. Though it has nothing to do with the downtime. Your package will be available on the website about 20 minutes after the GitHub action is done (for Netlify to upload the content to edges).

Thanks for reporting the issue.
