### ISSUE TITLE
Unpublish the RealityToolkit.gltf package

### ISSUE THREAD

**Issue by SimonDarksideJ** [openupm/openupm#3287]
Please read the guideline for [unpublishing a package](https://openupm.com/docs/modifying-upm-package.html#unpublishing-a-package) first.

#### What's the reason to unpublish the package entirely?
The forked repository is no longer maintained by the Reality Collective and is effectively superseded by the Siccity gltf package it was based from.  To our knowledge, this package is not used by any developers at this time.

#### What's the package name?
com.realitytoolkit.gltf / RealityToolkit.gLTF

#### Have you removed the package meta file and added the package name to the blocked-scopes.yml?
A PR has been raised for the removal of the package, the PR will also update the blocked-scopes file

**Comment by favoyang** [comment]
Approved via #3286
