### ISSUE TITLE
Unpublish package version

### ISSUE THREAD

**Issue by tratteo** [openupm/openupm#3294]
#### What's the reason to unpublish a version?
Wrong dependencies at the time of creation of tags
#### What's the package name?
com.tratteo.gibframe
com.tratteo.pury

#### Which version(s) you want to unpublish?
com.tratteo.gibframe v5.2.0
com.tratteo.pury v1.0.0

#### Have you removed or replaced the related Git tag(s)?
Yes, removed both

**Comment by favoyang** [comment]
Done. Please treat it as a one-time service for the onboarding package.

The public registry does not support unpublish existing versions except for a few edge cases. For bug fixes, please publish a new version instead.
