### ISSUE TITLE
Unpublish a Package Entirely

### ISSUE THREAD

**Issue by WAYN-Games** [openupm/openupm#3312]
Please read the guideline for [unpublishing a package](https://openupm.com/docs/modifying-upm-package.html#unpublishing-a-package) first.

#### What's the reason to unpublish the package entirely?
Packages are deprecated. No replacement is in the work and no support can be provided.

#### What's the package name?
com.wayngroup.requirementworkflow
com.wayngroup.stm

#### Have you removed the package meta file and added the package name to the blocked-scopes.yml?
Yes

**Comment by favoyang** [comment]
Done.
