### ISSUE TITLE
Package ReadMe does not render heading line if label is blank. (visual bug)

### ISSUE THREAD

**Issue by TolinSimpson** [openupm/openupm#3318]
#### Bug category

- [X] Website:

In GitHub repositories, if a markdown heading tag is left empty a line is rendered. Like this:

#

On the openUPM website when inspecting a package's ReadMe file empty heading tags display nothing.

I use empty heading tags to make my README look nice by separating information.

Compare:
https://openupm.com/packages/com.kitbashery.modular-ai/
&
https://github.com/Kitbashery/Modular-AI

Notice that at the bottom where I keep my copyright notice the heading line is not rendered on openUPM but is on GitHub.

Could this be a limitation of a 3rd party tool in the website's build pipeline?

**Comment by favoyang** [comment]
The empty H1 tag is still there, but our CSS framework didn't render it as GitHub.

Anyway using the empty H1 tag as a sep line didn't smell right.

Try four dash instead (markdown sep line)
```
----
```

Example: the bottom of https://github.com/favoyang/unity-action-sender/blob/master/README.md
