### ISSUE TITLE
CN mirror server error

### ISSUE THREAD

**Issue by wellshsu** [openupm/openupm#3326]
Publish success, but no archive file was found, here is details:
Cannot perform upm operation: Unable to add package [ep.u3d.library.base@0.1.9]:
  'https://package.openupm.cn:443/ep.u3d.library.base/-/ep.u3d.library.base-0.1.9.tgz' was not found [NotFound]
UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()

**Comment by favoyang** [comment]
A large package is blocking the sync process . It may get finished by tomorrow.

**Comment by wellshsu** [comment]
> 
Got it, add pkg limition or split sync pipeline of tiny-pkg and large-pkg maybe resonable.

**Comment by favoyang** [comment]
> Got it, add pkg limition or split sync pipeline of tiny-pkg and large-pkg maybe reasonable.

Anyway, our bottleneck is the extremely low bandwidth in the CN region, and don't have enough resources to improve it.

I may consider your suggestion.

The sync is finished.
