### ISSUE TITLE
Unpublish package version

### ISSUE THREAD

**Issue by BenWoodford** [openupm/openupm#3343]
Please read the guideline for [unpublishing a package version](https://openupm.com/docs/modifying-upm-package.html#modifying-or-deleting-a-published-version) first.

#### What's the reason to unpublish a version?
Incorrect package.json version number, and I messed up the public branch creation so needed to recreate it and rebase a load of commit history. This is a pretty new package thankfully, and we know with reasonable certainty that nobody will have pulled it down yet.

#### What's the package name?
com.strikervr.strikersdk

#### Which version(s) you want to unpublish?
0.4.1, 0.4.6

#### Have you removed or replaced the related Git tag(s)?
Yes

**Comment by favoyang** [comment]
Done.

At the time of writing, `com.strikervr.strikersdk` has only one published version `0.4.7`.
