### ISSUE TITLE
Website crash: out of memory

### ISSUE THREAD

**Issue by laicasaane** [openupm/openupm#3453]
#### Bug category

- [x] Website: issues related to browse or discover packages.

#### Steps to reproduce

- Open https://openupm.com/packages/ in MS Edge or Firefox
- Scrolling the package list for a while

#### What is expected?

- Can scroll till the end of the list

#### What is actually happening?

- The site crashes, somewhat frequently, with the reason: out of memory

**Comment by favoyang** [comment]
Hi @laicasaane, thanks for reporting the issue. I gonna spend some time on it.

**Comment by donatocayurin** [comment]
Thank you ❤️🙏

**Comment by donatocayurin** [comment]
❤️🙏

**Comment by favoyang** [comment]
Fixed by #4042.
