### ISSUE TITLE
npm ERR! code E502

### ISSUE THREAD

**Issue by Hugo-Pereira** [openupm/openupm#3463]
#### Bug category

- [x] Pipelines: issues related to publish or manage a package.

#### Steps to reproduce

Created a release on github, which triggered a build on openUPM, but got an error.
See https://dev.azure.com/openupm/openupm/_build/results?view=logs&buildId=25913&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=05a7d88e-decf-5c29-7849-5d16879a64a4

#### What is expected?

Build to succeed.

#### What is actually happening?

Build failed with error "npm ERR! 502 Bad Gateway - PUT https://package.***.com/com.didimo.sdk.core"

**Comment by favoyang** [comment]
Sorry for the inconvenience. The issue has been resolved.
