### ISSUE TITLE
unpublish com.tencent.puerts.core@1.4.0-rc.2

### ISSUE THREAD

**Issue by zombieyang** [openupm/openupm#3466]
Please read the guideline for [unpublishing a package version](https://openupm.com/docs/modifying-upm-package.html#modifying-or-deleting-a-published-version) first.

#### What's the reason to unpublish a version?
I put some wrong .meta file in this version 

#### What's the package name?
com.tencent.puerts.core

#### Which version(s) you want to unpublish?
1.4.0-rc.2

#### Have you removed or replaced the related Git tag(s)?
I removed

**Comment by favoyang** [comment]
Done

**Comment by zombieyang** [comment]
After this operate, openupm will not detect the newly pushed tag `upm/1.4.0-rc.2` anymore? [unpublishing a package version](https://openupm.com/docs/modifying-upm-package.html#modifying-or-deleting-a-published-version) didn't mention that.

I have published rc.3 so it is not a big problem. Just want to make a confirm.

**Comment by favoyang** [comment]
My mistake was to forget to remove the old release record. Anyway bumping to a new version is a good practice.
