### ISSUE TITLE
deploy-website-cn job fails

### ISSUE THREAD

**Issue by sschmid** [openupm/openupm#3496]
#### Bug category

- [ ] Website: issues related to browse or discover packages.
- [x] Pipelines: issues related to publish or manage a package.
- [ ] Registry: issues related to the registry server.
- [ ] Unity Editor: issues related to how OpenUPM works with the Unity Editor.
- [ ] Documentation
- [ ] Others

Just a heads-up:

`deploy-website-cn` job started failing
see GitHub Actions: https://github.com/openupm/openupm/actions

**Comment by favoyang** [comment]
The deploy-website-cn job is fixed: https://github.com/openupm/openupm/actions

Though during the server maintenance the registry cn-region is likely to be out of sync for a while. Track the process at https://discord.gg/FnUgWEP

**Comment by favoyang** [comment]
> Though during the server maintenance the registry cn-region is likely to be out of sync for a while. Track the process at https://discord.gg/FnUgWEP

The cn-region is fully recovered.
