### ISSUE TITLE
0.10.1

### ISSUE THREAD

**Issue by ldr123** [openupm/openupm#3531]
Please read the guideline for [unpublishing a package version](https://openupm.com/docs/modifying-upm-package.html#modifying-or-deleting-a-published-version) first.

#### What's the reason to migrate a version?

I want to replace repoUrl to https://github.com/focus-creative-games/hybridclr_unity.
Tell me what I need to do please, Thanks.

#### What's the package name?
com.focus-creative-games.hybridclr_unity

#### Which version(s) you want to move?
0.10.1

#### Have you removed or replaced the related Git tag(s)?
Yes

**Comment by favoyang** [comment]
Hi @ldr123,

I'm a little confused about your intention:
- Replace the repoUrl to https://github.com/focus-creative-games/hybridclr_unity. It seems only to have one Git tag 0.2.0?
- Or just remove 0.10.1 to let the pipelines rebuild it?

**Comment by ldr123** [comment]
Thx for your response.
I want replace the repoUrl to https://github.com/focus-creative-games/hybridclr_unity, and the pipelines depends the new repoUrl, so we need do something like fork upm trigger or others?
By the way, we will tag 0.10.2 on  https://github.com/focus-creative-games/hybridclr_unity.
So, what is the next thing?

**Comment by favoyang** [comment]
- The repoUrl updated in #3532
- v0.10.2 has been unpublished: https://openupm.com/packages/com.focus-creative-games.hybridclr_unity/?subPage=versions
- you can go ahead to create new Git tags at https://github.com/focus-creative-games/hybridclr_unity

**Comment by ldr123** [comment]
ok,thx
