### ISSUE TITLE
tgz file not fount for new released package on openupm.cn

### ISSUE THREAD

**Issue by SolarianZ** [openupm/openupm#3540]
I drafted a new release for my package and I can see this new release on openupm.cn, but I can't download this new release from openupm.cn:
```
Cannot perform upm operation: Unable to add package [com.greenbamboogames.playablegraphmonitor@1.0.8]:
  'https://package.openupm.cn/com.greenbamboogames.playablegraphmonitor/-/com.greenbamboogames.playablegraphmonitor-1.0.8.tgz' was not found [NotFound]
```

It is fine on opemupm.com.

**Comment by SolarianZ** [comment]
![err03](https://user-images.githubusercontent.com/11539008/201473022-450909a9-6b46-46c4-97f7-50745e4ddc6c.png)
![err01](https://user-images.githubusercontent.com/11539008/201473026-16ca13ae-58cd-4efe-a5ce-aae70802d9ec.png)
![err02](https://user-images.githubusercontent.com/11539008/201473028-04ed2c14-53a2-46b9-95de-519e8b8b041c.png)

**Comment by favoyang** [comment]
The tarball sync (from us to china) can be slower than the database sync for a while (10-30 minutes). The tarball is available at the time of writing.
