### ISSUE TITLE
Change name package

### ISSUE THREAD

**Issue by uurha** [openupm/openupm#3570]
I want to modify name of package because I want to make this package partial to other, but it will create a lot confusion for other users is I'll keep old name. 

https://github.com/openupm/openupm/pull/3569

**Comment by favoyang** [comment]
So you want to revert #3569?

**Comment by favoyang** [comment]
Oh, #3569 is not merged yet. So nothing to merge if you want to keep the original package name.

**Comment by uurha** [comment]
Yes, I closed pr and issue because when I tried to add package with new name, it was recommended to do not use "unity" in name)
