### ISSUE TITLE
Unpublish package version

### ISSUE THREAD

**Issue by MattGrayUL** [openupm/openupm#3600]
#### What's the reason to unpublish a version?
The com.ultraleap.openxr pre-release package was merged into the com.ultraleap.tracking package, making the pre-release obsolete. We would like to completely remove the ability to discover via OpenUPM to any users that have not already downloaded the com.ultraleap.openxr pre-release package

#### What's the package name?
com.ultraleap.tracking.openxr

#### Which version(s) you want to unpublish?
All versions

#### Have you removed or replaced the related Git tag(s)?
I have removed the tags

**Comment by favoyang** [comment]
All versions of `com.ultraleap.tracking.openxr` has been removed.

You can also submit a PR to remove the package meta file, to remove it completely from the website. https://github.com/openupm/openupm/blob/master/data/packages/com.ultraleap.tracking.openxr.yml
