### ISSUE TITLE
I need to change my package layout

### ISSUE THREAD

**Issue by joaoborks** [openupm/openupm#3712]
#### What's the package name?

[com.mygamedevtools.scene-loader](https://openupm.com/packages/com.mygamedevtools.scene-loader/) ([repo](https://github.com/mygamedevtools/scene-loader))

#### The reason to replace a published package?

- [ ] replace a fork with the official package repository
- [ ] replace an unmaintained fork with another fork
- [x] other

I need to update the UPM Package layout from `UPM package at the root path` to `UPM package at a sub-folder with UPM branch`.

#### Please provide the new source repository URL on GitHub.

[MyGameDevTools/Scene Loader](https://github.com/mygamedevtools/scene-loader)

#### Is the new UPM repository has at least one working Git tag? (Please test it with the Unity Editor)

It still doesn't have any tags generated under the new layout structure.

---

I have an additional question:
- Should I release a new package version under the new layout, or should I wait for the adjustments on OpenUPM side?

**Comment by favoyang** [comment]
OpenUPM detects the path of the package.json for your package name. So, you'll be able to place it in any sub-folder.

OpenUPM only tracks a versioned Git tag. After you restructure the layout, you can bump the version and create a new Git tag from the branch that contains the package, either from the main or the upm branch.

**Comment by joaoborks** [comment]
Hi @favoyang, thanks for the quick answer!

In this case I'd be having duplicated tags as well, but according to the documentation:

> In such cases the tag from the upm branch takes higher priority

I'll give it a shot this evening and let you know if I need further assistance.

**Comment by joaoborks** [comment]
It worked! 🚀 

I've successfully changed from `UPM package at the root path` to `UPM package at a sub-folder with UPM branch`.

Thank you for your assistance.

**Comment by favoyang** [comment]
> In this case I'd be having duplicated tags as well, but according to the documentation:
> 
> > In such cases the tag from the upm branch takes higher priority

Yes, Git tags with the "upm/" prefix or the "-upm" suffix get a high priority.

Glad to know it works.
