### ISSUE TITLE
"Latest" releases do not appear to be detected properly.

### ISSUE THREAD

**Issue by SimonDarksideJ** [openupm/openupm#3759]
#### Bug category

- [x] Website: issues related to browse or discover packages.
- [ ] Pipelines: issues related to publish or manage a package.
- [ ] Registry: issues related to the registry server.
- [ ] Unity Editor: issues related to how OpenUPM works with the Unity Editor.
- [ ] Documentation
- [ ] Others

#### Steps to reproduce
We updated all the packages in the RealityToolkit space to match the new UPM package format for pre-releases (previews are no longer detected as previews).

However, the new, latest "pre-releases" are not being marked as "latest" in the OpenUPM packages list.

![image](https://user-images.githubusercontent.com/1793042/221370101-8f946c76-341c-41ab-974a-e5fe6d0b5e67.png)

#### What is expected?

The latest published release should be the "latest"

#### What is actually happening?
The Previous release is marked as latest?

**Comment by favoyang** [comment]
It is related to a design issue with [semver](https://semver.org/)'s pre-release. It is too flexible.

Here I quote,
> A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version. Identifiers MUST comprise only ASCII alphanumerics and hyphens [0-9A-Za-z-]. Identifiers MUST NOT be empty. Numeric identifiers MUST NOT include leading zeroes. Pre-release versions have a lower precedence than the associated normal version. A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version. Examples: 1.0.0-alpha, 1.0.0-alpha.1, 1.0.0-0.3.7, 1.0.0-x.7.z.92, 1.0.0-x-y-z.--.

> Precedence for two pre-release versions with the same major, minor, and patch version MUST be determined by comparing each dot separated identifier from left to right until a difference is found as follows:
> 
> - Identifiers consisting of only digits are compared numerically.
> - Identifiers with letters or hyphens are compared lexically in ASCII sort order.
> - Numeric identifiers always have lower precedence than non-numeric identifiers.
> - A larger set of pre-release fields has a higher precedence than a smaller set, if all of the preceding identifiers are equal.

```
<valid semver> ::= <version core>
                 | <version core> "-" <pre-release>
                 | <version core> "+" <build>
                 | <version core> "-" <pre-release> "+" <build>

...

<pre-release> ::= <dot-separated pre-release identifiers>

<dot-separated pre-release identifiers> ::= <pre-release identifier>
                                          | <pre-release identifier> "." <dot-separated pre-release identifiers>

```

A popular pattern is to use a dot to separate one pre-release identifier and one numeric identifier, like `preview.1`. But in your case, two pre-release identifies `preview.1` and `pre-release.2` are compared by ASCII sort order (`preview` > `pre-release`)

For OpenUPM, only the latest version of a package is getting compared with the newly published version to decide which tag to use - `latest` or `patch`. I manually fixed 5 packages below, to use `pre-release.x` as the lastest tag. If you stay with it we're good.

- com.realitytoolkit.core
- com.realitytoolkit.devtools
- com.realitytoolkit.metaplatform
- com.realitytoolkit.spatial-persistence
- com.realitytoolkit.spatial-persistence.asa

This package only contains the `preview` pre-release identifier. If you change it to `pre-release` text, notify me here for a manual fix.
- com.realitytoolkit.pico

**Comment by favoyang** [comment]
An online tool to test semver - https://semvercompare.azurewebsites.net/?version=1.0.0-preview.18&version=1.0.0-pre-release.19

It's not the library we used, but the behavior should be similar.

**Comment by SimonDarksideJ** [comment]
The Pico package has now also been updated (was waiting on a query).  Please update the pre-release version to latest.

**Comment by SimonDarksideJ** [comment]
P.S. is there a way to cleanup and de-list the "Preview" versions, we have updated the package definitions to exclude them but they are still showing.

**Comment by favoyang** [comment]
> The Pico package has now also been updated (was waiting on a query). Please update the pre-release version to latest.

Done.


> P.S. is there a way to cleanup and de-list the "Preview" versions, we have updated the package definitions to exclude them but they are still showing.

The Unity package manager (Pacman) doesn't support package deprecation. The only way to delist existing versions is to unpublish them from the registry. However, it's not a recommended practice to unpublish existing versions from a public registry, which breaks the backward compatibility. Please fill out [this form](https://github.com/openupm/openupm/issues/new?assignees=&labels=&template=unpublish_version.md) if you insist.

The `gitTagIgnore` only works for unpublished Git tags.

**Comment by SimonDarksideJ** [comment]
We've had to do an emergency update and it seems the "fix" to set the pre-release tag to latest is now preventing the newest version being detected as latest.  Not sure what the best fix is, as Unity is unable to see the newest releases.

Thoughts @favoyang ?

**Comment by favoyang** [comment]
I installed com.realitytoolkit.core@1.0.0-preview.18

Here's what I get

![image](https://user-images.githubusercontent.com/125390/221726773-1a447bfe-2bf3-4a08-aeb0-1c2e3da6737d.png)

I can see 1.0.0-pre-release.19, 1.0.0-pre.20 in the version history tab. But Unity didn't prompt me that they are new versions that I could update to

On our server
```
dist-tags:
latest: 1.0.0-pre-release.19      patch@1.0.0-pre.20: 1.0.0-pre.20
```

I manually set `1.0.0-pre-release.19` as lastet yesterday. Then you published `1.0.0-pre.20`.

![image](https://user-images.githubusercontent.com/125390/221727380-e7394588-d5f4-45af-a069-44ae676b19ec.png)

As mentioned before, `pre.20 < pre-release.19`, because `pre < pre-release` in string sort. So `1.0.0-pre.20` is not being marked as latest.

I can see that two issues here
- You need a stable pre-release identifier, preview, pre-release, or pre.
- Unity seems to treat `preview` as a special pre-release identifier. It didn't always respect to the `latest` dist-tag on the server. I will do more tests and back to you. But please notice that the behavior may vary for different Unity editors. I tested with 2022.2.7f1

**Comment by favoyang** [comment]
> * Unity seems to treat `preview` as a special pre-release identifier. It didn't always respect to the `latest` dist-tag on the server. I will do more tests and back to you. But please notice that the behavior may vary for different Unity editors. I tested with 2022.2.7f1

I've done a few tests against 2022.2.7f1.

I prepare a test package with four versions to test different pre-release identifiers.

- 1.0.0-pre.1 (installed)
- 1.0.0-preview.2
- 1.0.0-prerelease.3
- 1.0.0-pre-release.4 (latest dist-tag on the server)

![image](https://user-images.githubusercontent.com/125390/221752306-bb386021-8fda-4e96-b292-ed86b16afbd9.png)

The result shows that Unity follows the semver rules to compare pre-release identifiers. As a result, `preview` always has higher precedence than others listed below.
```
pre.1 => ['pre', 1]
preview.2 => ['preview', 2]
prerelease.3 => ['prerelease', 3]
pre-release.4 => ['pre-release', 4]

'pre' < 'pre-release' < 'prerelease' < 'preview'
```
![image](https://user-images.githubusercontent.com/125390/221753764-948b888a-8a3b-4fa4-aefb-7f288d5988b7.png)

Then your choices are
- Force unpublish all existing `preview` versions and choose one stable pre-release identifier to use (pre or prerelease, or pre-release)
- Revert back to use the `preview` pre-release identifier with the next version, since it naturally gets higher precedence, it will appear as the latest.

**Comment by SimonDarksideJ** [comment]
Thanks for all your testing @favoyang it is really appreciated and confirms my suspicions that although Unity have "updated" their release cycles for packages, they have actually not updated Unity to work with their new vision.

I suspect for any package previously publishing a "preview" is also going to run in to this problem, due to this
https://docs.unity3d.com/Manual/pack-preview.html

WhIch they "say" is taking effect from 2022, however, we've seen issues in earlier releases.  So because Unity orders the older "preview" before the new "pre" notation for preview (might not affect the new experimental tag "exp"), existing packages are going to suffer.

We are going to take a hard line and implement a breaking change for now, unpublish the existing RealitToolkit packages, remove older tags and rebaseline back to "pre.1"

Thanks again for your help and I "may" create a testing package to publish to OpenUPM to create an issue as a bug report for Unity to digest (if I have the energy)

**Comment by favoyang** [comment]
Before you make a decision please notice that all the `Exp`, `Pre-Release` or `Pre` flags (the yellow label) mentioned in [the doct](https://docs.unity3d.com/Manual/pack-preview.html) are applied to Unity packages only, not to custom packages. In fact, I can not find such metadata in the Unity registry, it seems to be fetched from somewhere else.

The screenshot shows how internal packages and custom packages are treated differently for the `Exp` label.
![image](https://user-images.githubusercontent.com/125390/221832519-97e7219f-2c28-4b3d-bb9a-0caf58e49827.png)

For custom packages, all you get is a label of the pre-release identifier in the detail page.

![image](https://user-images.githubusercontent.com/125390/221831638-5daa4318-a6b1-48ac-9837-21cb204887e9.png)
![image](https://user-images.githubusercontent.com/125390/221831768-86c2a875-2868-4f61-8bf7-4dc700c4d66c.png)
![image](https://user-images.githubusercontent.com/125390/221832057-ec3a5c34-6cd6-4025-b29d-1fdb658ea58f.png)

Please let me know your decision for #3763 after considering the information above.

**Comment by SimonDarksideJ** [comment]
Yeah, Unity are not being very consistent for how pre-release packages should be handled going forward, but it will be far easier in the long run if we rebaseline our packages using their "new new new" standard and then work from there.
We've checked with our User base and this should not affect them in the short term.

Also published a pull request to remove the packages and I'll resubmit them at a future date once all the repositories (we have quite a few) have all been cleaned up @favoyang.
https://github.com/openupm/openupm/pull/3764

**Comment by SimonDarksideJ** [comment]
After a lot of hustle and bustle, the reality toolkit packages have been resubmitted back to OpenUPM
https://github.com/openupm/openupm/pull/3765

Thanks again @favoyang
