### ISSUE TITLE
Unpublish com.kl6g.kore

### ISSUE THREAD

**Issue by Kuuo** [openupm/openupm#3775]
Please read the guideline for [unpublishing a package](https://openupm.com/docs/modifying-upm-package.html#unpublishing-a-package) first.

#### What's the reason to unpublish the package entirely?
this package is now for personal use only. But in a small chance will be published again in the future.

#### What's the package name?
com.kl6g.kore

#### Have you removed the package meta file and added the package name to the blocked-scopes.yml?
yes, package meta file has removed in pr #3762 , it's OK for me to not avoid re-submitting by adding the package name to blocked-scopes.yml

**Comment by favoyang** [comment]
Closed by https://github.com/openupm/openupm/pull/3762. The website will take about 30mins to rebuild for the changes.
