### ISSUE TITLE
trying to add a package doesn't every make the 'submit' button enabled

### ISSUE THREAD

**Issue by gekidoslair** [openupm/openupm#38]
I've run into this a few times when trying to submit a new package - no matter what I do the 'submit package' button never goes green (so I can create the pull request)

Ideas? Not sure if this is an openUPM issue or  github issue?

**Comment by favoyang** [comment]
It happens on specific url? I’ll check the logic later.

**Comment by gekidoslair** [comment]
happens after I click 'upload package' on the openupm site, which takes me here:

https://github.com/openupm/openupm/new/master/

- the github page is what never lets me complete making the fork / PR

**Comment by gekidoslair** [comment]
for example:

https://github.com/openupm/openupm/new/master/?filename=data%2Fpackages%2Fca.andydbc.unity-texture-packer.yml&value=name%3A%20ca.andydbc.unity-texture-packer%0AdisplayName%3A%20Texture%20Channel%20Packer%0Adescription%3A%20%3E-%0A%20%20%3Ahammer%3A%20Utility%20to%20combine%20color%20channels%20from%20different%20textures%20into%20a%0A%20%20single%20output.%0ArepoUrl%3A%20%27https%3A%2F%2Fgithub.com%2Fandydbc%2Funity-texture-packer%27%0ArepoBranch%3A%20master%0AparentRepoUrl%3A%20null%0AlicenseSpdxId%3A%20null%0AlicenseName%3A%20MIT%0Atopics%3A%0A%20%20-%20asset-management%0Ahunter%3A%20pixelwizards%0AgitTagIgnore%3A%20%27%27%0AcreatedAt%3A%201579921084542%0A&message=chore(data)%3A%20new%20package%20ca.andydbc.unity-texture-packer

**Comment by gekidoslair** [comment]
the 'propose new file' button never goes green for whatever reason :{

**Comment by favoyang** [comment]
The url works for me. Can you make a full screenshot of your GitHub page? Perhaps the browser console as well?

**Comment by gekidoslair** [comment]
lol of course as soon as I click the link to capture the screenshot, it works fine. 

will grab logs  etc if it happens again (it has a couple of times so far)

**Comment by favoyang** [comment]
@gekidoslair FYI: I created and merged PR from your fork:
- https://github.com/gekidoslair/openupm/tree/patch
- https://github.com/gekidoslair/openupm/tree/patch-4

https://openupm.com/packages/ca.andydbc.unity-texture-packer/
https://openupm.com/packages/com.pixelwizards.lightprobeplacement/
