### ISSUE TITLE
Bug: OpenUPM crawling unavailable, all packages stating they are disconnected from repositories.

### ISSUE THREAD

**Issue by SimonDarksideJ** [openupm/openupm#3823]
## Bug report

Bug: OpenUPM crawling is unavailable, and all packages state they are disconnected from repositories.

The status page shows no issues present.

#### Bug category

- [X] Website: issues related to browse or discover packages.

#### Steps to reproduce

View any package on the OpenUPM site, see the image

#### What is expected?

Packages should be trawling and available

#### What is actually happening?

New updates are not being updated and the site is static.

#### Other relevant information
![image](https://user-images.githubusercontent.com/1793042/227508763-1b8641d4-fb0a-4929-8a21-5a6b2e0c1d90.png)

**Comment by favoyang** [comment]
Thanks for reporting the issue.

It makes sense as GitHub changed its RSA ssh host key a few hours ago. https://github.blog/2023-03-23-we-updated-our-rsa-ssh-host-key/. Our server rejects the connection to GitHub and treats it as a man-in-the-middle attack.

It shall take 1-2h to fix the entire website.

**Comment by favoyang** [comment]
Closed by https://github.com/openupm/openupm/commit/62e937ae294af23c3436c1694a7555d67dd57a2e and https://github.com/openupm/openupm/commit/3ca23076fadcf8c97da564155b237162dc4ef800
