### ISSUE TITLE
Unpublish package version

### ISSUE THREAD

**Issue by ArtemVetik** [openupm/openupm#3882]
Please read the guideline for [unpublishing a package version](https://openupm.com/docs/modifying-upm-package.html#modifying-or-deleting-a-published-version) first.

#### What's the reason to unpublish a version?
I checked how automatic version updates work, and in fact all versions except 1.0.0 were test versions and did not make any significant changes.
#### What's the package name?
com.agava.merge2
#### Which version(s) you want to unpublish?
1.0.1
1.0.2
1.0.3
1.0.8
1.0.9
#### Have you removed or replaced the related Git tag(s)?
I have removed the tags

**Comment by favoyang** [comment]
Done.

You may need to resolve the Unity Package Manager's dependency manually.
