### ISSUE TITLE
Unpublish com.razensoft.functional

### ISSUE THREAD

**Issue by Razenpok** [openupm/openupm#3893]
Please read the guideline for [unpublishing a package](https://openupm.com/docs/modifying-upm-package.html#unpublishing-a-package) first.

#### What's the reason to unpublish the package entirely?
This package has been superseded by [CSharpFunctionalExtensions.UniTask](https://github.com/Razenpok/CSharpFunctionalExtensions.UniTask)

#### What's the package name?
[Razensoft.Functional](https://github.com/Razenpok-Graveyard/Razensoft.Functional)

#### Have you removed the package meta file and added the package name to the blocked-scopes.yml?
#3892
I've added `"private": true"` to the package.json to avoid re-submitting

**Comment by favoyang** [comment]
Closed by #3892

**Comment by favoyang** [comment]
Please notice that the published versions are remaining on the registry for backward compatibility unless you intend to remove them with a good reason.

**Comment by Razenpok** [comment]
Yep, that's good. Thanks!
