### ISSUE TITLE
error when change package name

### ISSUE THREAD

**Issue by pirunxi** [openupm/openupm#4074]
## Unpublish version request

package com.focus-creative-games.hybridclr_unity.

#### What's the reason to unpublish a version?

we change package name from com.focus-creative-games.hybridclr_unity to com.code-philosophy.hybridclr recently. We found that 
building pipeline run failed. How can we fix the problem?  Do we have to unpublish the package?

#### What's the package name?

com.focus-creative-games.hybridclr_unity

#### Which version(s) you want to unpublish?

all.

#### Have you removed or replaced the related Git tag(s)?

no.

**Comment by favoyang** [comment]
You can update the package meta file: https://github.com/openupm/openupm/blob/master/data/packages/com.focus-creative-games.hybridclr_unity.yml

Steps
1. open the link and edit the file
2. change filename to `new-name`.yml
3. update `name` field to `new-name`
4. update `minVersion` field to `3.0.0`
5. submit the PR

The keep existing versions of the old name package are retained on the registry for backward compatibility.

**Comment by pirunxi** [comment]
thanks very much!!!

**Comment by favoyang** [comment]
The entry has been renamed to [`com.code-philosophy.hybridclr`](https://github.com/openupm/openupm/blob/master/data/packages/com.code-philosophy.hybridclr.yml#L1). Old versions below `3.0.0` will be kept on the registry with the old name. The website will be updated in 2 hours.

**Comment by pirunxi** [comment]
thanks!
