### ISSUE TITLE
Tag error?  Tags not recognised on package com.ethar.geopose

### ISSUE THREAD

**Issue by SimonDarksideJ** [openupm/openupm#4076]
#### Bug category

- [ ] Website: issues related to browse or discover packages.
- [ ] Pipelines: issues related to publish or manage a package.
- [X] Registry: issues related to the registry server.
- [ ] Unity Editor: issues related to how OpenUPM works with the Unity Editor.
- [ ] Documentation
- [ ] Others

#### Steps to reproduce

Check package ```com.ethar.geopose``` which uses a regex to identify package prefixed with "upm" (as the repo delivers to UPM and C#)
[https://openupm.com/packages/com.ethar.geopose](https://openupm.com/packages/com.ethar.geopose)

The Regex used is:

```gitTagPrefix: upm.*```

Which should pick up the tags ```upm-v1.0.0```

#### What is expected?

The package tags for ```upm-v1.0.0``` should be identified and listed

#### What is actually happening?

No package versions are identified

**Comment by favoyang** [comment]
The `gitTagPrefix` field is plain text, not a regular expression string. Please update the value to `upm-` for the intention.
