### ISSUE TITLE
Feature Request: Interpret Semantic Version

### ISSUE THREAD

**Issue by sliptrixx** [openupm/openupm#4194]
#### Feature category

- [ ] Website: improve the way to browse or discover packages.
- [x] Pipelines: improve the way to publish or manage a package.
- [ ] Registry: improve the registry server.
- [ ] Unity Editor: improve how OpenUPM works with the Unity Editor.
- [ ] Documentation
- [ ] Others

#### What problem does this feature solve?
A few open-source packages out there added to the registry by other users don't follow the semver convention. OpenUPM doesn't detect these tags because of the convention. For example, if a package was tagged as `v1.2` instead of `v1.2.0`, OpenUPM ignores it. 

#### How should this be implemented in your opinion?
Being more flexible about what is considered a valid tag will go a long way. For example, `v1.2` can be interpreted as `v1.2.0`, or even a step further, `v2` can be interpreted as `v2.0.0`.

#### Are you a regular backer or sponsor at [patreon.com/openupm](https://www.patreon.com/openupm)?
No

#### Are you willing to work on this yourself?
Maybe. If resources are stretched thin, I can familiarize myself with the codebase and try to implement it.

**Comment by favoyang** [comment]
The NPM system follows [Semantic Versioning](https://semver.org/). This means the registry won't accept packages that don't match these rules. This is helpful in only a few cases where the version number in the Git tag doesn't match the one in package.json.  For instance, if you tag it as `v2`, but the package.json says `v2.0.0`, it's better to talk to the author and keep things the same.

OpenUPM pipelines can not modify the version on the fly. It only packs content.
