### ISSUE TITLE
Max 10 packages per scope?

### ISSUE THREAD

**Issue by mvriel** [openupm/openupm#4338]
#### Bug category

- [ ] Website: issues related to browse or discover packages.
- [ ] Pipelines: issues related to publish or manage a package.
- [x] Registry: issues related to the registry server.
- [x] Unity Editor: issues related to how OpenUPM works with the Unity Editor.
- [ ] Documentation
- [ ] Others

#### Steps to reproduce

Add `eu.netherlands3d` as a scope to the Scoped Registries in Project Settings and see that `eu.netherlands3d.tiles3d` is missing in "My Registries"; add `eu.netherlands3d.tiles3d` as an additional scope and see it is present.

#### What is expected?

With the scope `eu.netherlands3d` I should also see the package `eu.netherlands3d.tiles3d` in "My Registries".

#### What is actually happening?

It is not there. See reproduction steps.

#### Other relevant information

Unless I am seeing this incorrectly, I count 10 `eu.netherlands3d` packages in my listing. Because I can discover the package when I add that scope explicitly, I have a gut feeling that this is a pagination issue. Either the OpenUPM registry returns 10 results and does not offer pagination; or Unity UPM does not have pagination when it comes to Scoped Registries. I do not know whether this is _actually_ the case, but it sounds a lot like it and I hope you know more about this and know of a fix?

**Comment by favoyang** [comment]
It is definitely a bug for the search endpoint that UPM uses to detect packages for a given scope.

**Comment by favoyang** [comment]
The issue has been resolved.
