### ISSUE TITLE
Timeout trying to download packages from openupm

### ISSUE THREAD

**Issue by jarussi** [openupm/openupm#4339]
#### Bug category

- [ ] Website: issues related to browse or discover packages.
- [ ] Pipelines: issues related to publish or manage a package.
- [ ] Registry: issues related to the registry server.
- [ ] Unity Editor: issues related to how OpenUPM works with the Unity Editor.
- [ ] Documentation
- [x] Others

#### Steps to reproduce
We are experiencing a high number of timeout trying to download packages from openupm. This started a few weeks ago and were crashing our build pipelines. 
We were able to reproduce with a simple python script (I used python because it was easier for me to reproduce).

I created the python script as below for the dependencies for my project that I download from openupm:
```python
import requests

data = {
    "com.coffee.unmask": "1.4.1",
    "com.cysharp.unitask": "2.3.3",
    "com.mygamedevtools.extensions": "1.4.0",
    "com.mygamedevtools.fps-counter": "1.5.0",
    "com.mygamedevtools.scene-loader": "2.1.1",
    "com.mygamedevtools.script-template": "3.4.0",
    "com.nomnom.regex-rename": "1.1.4"
}

for key, value in data.items():
    response = requests.get(f'https://package.openupm.com/{key}/-/{key}-{value}.tgz', timeout=20)
    print(f'got package {key}')
```
Sometimes it runs smoothly, most of the times I get timeouts trying to download the package.
```
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='openupm.sfo2.cdn.digitaloceanspaces.com', port=443): Read timed out. (read timeout=20)
```

#### What is expected?
It should download the package without timeouts.

#### What is actually happening?
More than often I receive a timeout trying to download the packages.
This is the pipeline error that we receive:
```
[Package Manager] Done resolving packages in 149.89s seconds
[Licensing::Client] Successfully resolved entitlement details
An error occurred while resolving packages:
  One or more packages could not be added to the local file system:
    com.mygamedevtools.fps-counter: connect ETIMEDOUT 205.185.216.10:443
    com.mygamedevtools.script-template: connect ETIMEDOUT 205.185.216.10:443
```

#### Other relevant information
We use the python script just for fast testing pourpose, but the error is happening during pipelines or local project installation.

**Comment by favoyang** [comment]
Sure, here's the text with improved grammar and readability:

I assume that the Python request with a timeout of 20 seconds will raise a timeout error if the download takes longer than 20 seconds.

The remaining error messages indicate that you have connected to our CDN server at 205.185.216.10 and are experiencing a network timeout issue.

There is a similar issue documented at https://github.com/openupm/openupm/issues/3403, but unfortunately, it doesn't have a clear solution yet.

The Digital Ocean CDN at 205.185.216.10 is an anycast IP that will forward you to a geo server located near your location.

You might want to run the `mtr -rwc 15 openupm.sfo2.cdn.digitaloceanspaces.com` command to determine which CDN server you are connecting to.

Alternatively, you can use the Python script without specifying the timeout argument to assess how frequently it fails. It's possible that Unity may also have a hardcoded package download timeout, but I am not yet aware of those details.

**Comment by jarussi** [comment]
thank you for the fast reply @favoyang ! 

I ran the command mtr and got this result:
```
Start: 2023-10-23T16:27:20-0300
HOST: MacBook-Pro-de-mlwkt500-4.local    Loss%   Snt   Last   Avg  Best  Wrst StDev
  1.|-- 192.168.5.1                         0.0%    15    2.6   3.7   2.5   5.5   1.0
  2.|-- menuvivofibra                       0.0%    15    3.2   4.3   2.7   7.7   1.4
  3.|-- ???                                100.0    15    0.0   0.0   0.0   0.0   0.0
  4.|-- 152-255-153-32.user.vivozap.com.br  0.0%    15    8.1   8.1   5.5  12.6   2.1
  5.|-- 187-100-194-6.dsl.telesp.net.br    93.3%    15    9.8   9.8   9.8   9.8   0.0
  6.|-- ???                                100.0    15    0.0   0.0   0.0   0.0   0.0
  7.|-- ???                                100.0    15    0.0   0.0   0.0   0.0   0.0
  8.|-- 151.139.92.6                        0.0%    15    7.4  10.0   7.4  13.5   1.6
  9.|-- 151.139.92.17                       0.0%    15   13.3   9.2   6.8  15.5   2.3
 10.|-- map2.hwcdn.net                      0.0%    15    6.8   9.4   6.8  12.9   1.8
```

I'm not an expert, but it seems like a lot of package loss (I'm from Brazil btw).

I did some tweeks in the python script as you said. I didn't left without a timeout, I just set a really high one - 100 seconds)  and I still got timeouts. It seems like it happens more often with some packages than others .. does it make any sense?

Do you know if maybe I could force using a server that is located closer to me?

**Comment by favoyang** [comment]
From the route trace logs, the connection was routed to a CDN server located in Osasco, Brazil, with the IP address 151.139.92.17. It seems correct based on your location.

The packet loss against certain intermediate servers is not necessarily a problem because many network devices are configured not to respond to ICMP requests, or due to network filters that prevent ICMP traffic. You have 0% loss against the final hop, which shows that the network may be functional. However, you can verify this by simply running `ping -c 15 openupm.sfo2.cdn.digitaloceanspaces.com` and checking for packet loss in the summary. If there is packet loss, then your ISP may have a problem.

The largest package is `com.coffee.unmask-1.4.1.tgz`, which is 1.7MB. It should be downloaded within a few seconds.

Could you please run the test on a different network or location?

So far, there is no way to define an alternative CDN server at a specified location.

**Comment by jarussi** [comment]
Running from my local machine, this is the result of the ping command - no package loss.
```
ping -c 15 openupm.sfo2.cdn.digitaloceanspaces.com
PING cds.b5g9b8e4.hwcdn.net (205.185.216.10): 56 data bytes
64 bytes from 205.185.216.10: icmp_seq=0 ttl=57 time=9.725 ms
64 bytes from 205.185.216.10: icmp_seq=1 ttl=57 time=8.659 ms
64 bytes from 205.185.216.10: icmp_seq=2 ttl=57 time=7.314 ms
64 bytes from 205.185.216.10: icmp_seq=3 ttl=57 time=8.238 ms
64 bytes from 205.185.216.10: icmp_seq=4 ttl=57 time=7.388 ms
64 bytes from 205.185.216.10: icmp_seq=5 ttl=57 time=8.659 ms
64 bytes from 205.185.216.10: icmp_seq=6 ttl=57 time=8.042 ms
64 bytes from 205.185.216.10: icmp_seq=7 ttl=57 time=8.235 ms
64 bytes from 205.185.216.10: icmp_seq=8 ttl=57 time=7.762 ms
64 bytes from 205.185.216.10: icmp_seq=9 ttl=57 time=7.357 ms
64 bytes from 205.185.216.10: icmp_seq=10 ttl=57 time=7.883 ms
64 bytes from 205.185.216.10: icmp_seq=11 ttl=57 time=8.726 ms
64 bytes from 205.185.216.10: icmp_seq=12 ttl=57 time=7.318 ms
64 bytes from 205.185.216.10: icmp_seq=13 ttl=57 time=8.353 ms
64 bytes from 205.185.216.10: icmp_seq=14 ttl=57 time=9.011 ms

--- cds.b5g9b8e4.hwcdn.net ping statistics ---
15 packets transmitted, 15 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 7.314/8.178/9.725/0.681 ms
```

Running my python script from a machine located in the US (I can't say for sure where). I ran the script 5 times, and most of them got the same result. Most of the downloads happen really really fast.
```
got package com.nomnom.regex-rename in 0.06567 seconds
got package com.cysharp.unitask in 0.067505 seconds
got package com.mygamedevtools.script-template in 0.066111 seconds
got package com.mygamedevtools.extensions in 0.064303 seconds
got package com.coffee.unmask in 0.067329 seconds
got package com.mygamedevtools.fps-counter in 0.066645 seconds
got package com.mygamedevtools.scene-loader in 0.076142 seconds
```

Running my python script from my local machine located in Brazil. You can see I got some 20 seconds responses and other times I got timeout trying to download.
```
got package com.coffee.unmask in 0.04233 seconds
got package com.cysharp.unitask in 0.054498 seconds
got package com.mygamedevtools.extensions in 20.053787 seconds
got package com.mygamedevtools.fps-counter in 0.048369 seconds
got package com.mygamedevtools.scene-loader in 0.04562 seconds
got package com.mygamedevtools.script-template in 0.051381 seconds
got package com.nomnom.regex-rename in 0.049832 seconds
```

I also ran mtr from the us machine and got this as a response:
```
mtr -rwc 15 openupm.sfo2.cdn.digitaloceanspaces.com
Start: 2023-10-24T11:14:15-0300
HOST: bastion        Loss%   Snt   Last   Avg  Best  Wrst StDev
  1.|-- localhost      40.0%    15  4944. 5618. 540.6 8230. 2563.9
  2.|-- 151.139.60.3    0.0%    15   10.5  10.6  10.5  10.9   0.1
  3.|-- 151.139.60.8    0.0%    15   10.4  10.5  10.4  10.6   0.0
  4.|-- map2.hwcdn.net  0.0%    15   10.5  10.5  10.4  10.7   0.1
```

It seems that there is a lot less hops when accessing from the US.

I'm not really sure what to do here. Any help would be apreciated.

**Comment by favoyang** [comment]
I appreciate the thorough report. While it may not provide an immediate solution, it does point toward a potential issue with your network connection to the Brazil server.

To narrow down the problem, you could try using a different local ISP (like your office or cell phone network) to see if the issue persists. If the problem remains, it might indicate a broader network issue in Brazil. In that case, I'll proceed to contact Digital Ocean to conduct further investigations on their Brazil server.

Right now, I don't have a workaround except you could try using a proxy or VPN service as a temporary solution.

**Comment by jarussi** [comment]
I tried the tests you suggested:

my home internet provider
```
got package com.coffee.unmask in 0.861248 seconds
got package com.cysharp.unitask in 0.908733 seconds
got package com.mygamedevtools.extensions in 0.881399 seconds
got package com.mygamedevtools.fps-counter in 1.040427 seconds
got package com.mygamedevtools.scene-loader in 0.852942 seconds
got package com.mygamedevtools.script-template in 1.071144 seconds
got package com.nomnom.regex-rename in 0.825049 seconds
```

my office internet provider
```
got package com.coffee.unmask in 0.057495 seconds
got package com.cysharp.unitask in 0.060288 seconds
got package com.mygamedevtools.extensions in 0.07056 seconds
got package com.mygamedevtools.fps-counter in 0.049504 seconds
got package com.mygamedevtools.scene-loader in 0.672716 seconds
got package com.mygamedevtools.script-template in 0.065593 seconds
got package com.nomnom.regex-rename in 0.070241 seconds
```

my 4G mobile signal
```
got package com.coffee.unmask in 0.392332 seconds
got package com.cysharp.unitask in 0.125964 seconds
got package com.mygamedevtools.extensions in 0.084423 seconds
got package com.mygamedevtools.fps-counter in 0.097605 seconds
got package com.mygamedevtools.scene-loader in 0.082523 seconds
got package com.mygamedevtools.script-template in 0.097982 seconds
got package com.nomnom.regex-rename in 0.118702 seconds
```

I had no issue this time running the test from 3 different locations. No timeout what so ever (and I ran each test 3 or 4 times).

I'll see if I can do some kind of workaround to use an international vpn service. Maybe this will help with the timeouts. Thanks a lot @favoyang and let me know if Digital Ocean gives any feedback. Maybe even shutting down the Brazilian server and redirect to the US maybe ... It's best to take a few seconds to download than receiving a timeout.

**Comment by favoyang** [comment]
Your tests have demonstrated that debugging network issues can be challenging, especially when the problem isn't consistent. However, I also observed a recent network issue on Digital Ocean, which has since been resolved. It's possible that this incident was the root cause of the problem you encountered. You can find more information about it here: https://status.digitalocean.com/incidents/gp9bzm1hnlk4.

**Comment by jarussi** [comment]
@favoyang I ran my test several times (around 500 downloads) and haven't got a single timeout. I believe you are right and maybe the issue was on Digital Ocean all along.

I really appreciate your time and help, think we should close this issue?

**Comment by favoyang** [comment]
Thanks for your investigation! Issue closed.
