### ISSUE TITLE
Error message on package submit: "c.form.options.some is not a function"

### ISSUE THREAD

**Issue by sambaas** [openupm/openupm#4343]
#### Bug category

- [x] Website: issues related to browse or discover packages.
- [ ] Pipelines: issues related to publish or manage a package.
- [x] Registry: issues related to the registry server.
- [ ] Unity Editor: issues related to how OpenUPM works with the Unity Editor.
- [ ] Documentation
- [ ] Others

#### Steps to reproduce

1. Submit a new OpenUPM package ( for instance https://github.com/Netherlands3D/ColladaExport )
2. Select 'main' branch in Branch dropdown

#### What is expected?

The ability to select the package.json in the dropdown underneath the branch selection

#### What is actually happening?

An error message appears underneath the Branch dropdown:
```c.form.options.some is not a function```

#### Other relevant information

Tested with two different packages, on different systems

**Comment by favoyang** [comment]
Hi @sambaas,

Thanks for reporting the issue. It shall be fixed in the next build (about half an hour later).

**Comment by sambaas** [comment]
@favoyang Great, thanks! Thats a fast fix 💪
