### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by bdovaz** [openupm/openupm#4353]
If you try to download 1.1.2, it gives a: File not found

https://package.openupm.com/com.ar-tracking.dtrack/

tarball link from previous page: https://package.openupm.com/com.ar-tracking.dtrack/-/com.ar-tracking.dtrack-1.1.2.tgz

@favoyang is this a recent error, is there a problem with the CDN or maintenance work that we are not aware of?

Thanks!

**Comment by favoyang** [comment]
Thank you for the update. It appears that the issue was related to server maintenance, and it should be resolved now. I will give it a try to confirm.

**Comment by favoyang** [comment]
I think we're good here.
