### ISSUE TITLE
Invisible code blocks on openupm.com

### ISSUE THREAD

**Issue by ze0nni** [openupm/openupm#4393]
#### Bug category

- [ ] Website: 

#### Steps to reproduce

Open any package page

#### What is expected?

Read package code examples

#### What is actually happening?

Some or all keywords are invisible

![image](https://github.com/openupm/openupm/assets/1662527/99da3062-c2f2-4fe8-9f1e-be3277590581)

**Comment by favoyang** [comment]
@ze0nni,  Thanks for report the issue. I confirmed it is a color issue in the light theme.

Workaround - switch to the dark theme.

https://openupm.com/packages/com.cysharp.unitask/

**Comment by favoyang** [comment]
Fixed by https://github.com/openupm/openupm-next/commit/4f64e005828d0a4fe650f9251143c188a1fb23f0
