### ISSUE TITLE
screwed up PR ;\

### ISSUE THREAD

**Issue by gekidoslair** [openupm/openupm#44]
submitted a package but didn't click the final 'submit PR' button - so it doesn't show up in the PR list, but then I tried to submit a second one - but that failed because the yml file didn't match the package name ;{

https://github.com/openupm/openupm/runs/412023819

I think this might be related to the issue I had before submitted packages - maybe I haven't been fully submitting them properly and they get stuck in this limbo land where the file has been created by the PR hasn't been fully submitted?

**Comment by favoyang** [comment]
I'll explain what happens. When creating a PR via GitHub website it takes 2 step:
- GitHub helps you fork the upstream repository, then adding your changes to a branch named patch-number quitely.
- GitHub guides you to create a PR by comparing your patch branch and the upstream master. (What the final 'submit PR' button do). If you forget to do this, you can always go to the branch page, then click the 'New pull request' button.

![image](https://user-images.githubusercontent.com/125390/73230994-ff86c900-41b9-11ea-90e7-0f0fc8f24132.png)

In your case, you stopped at step 1, then re-prepared a new PR. The GitHub website/you somehow, changed the filename to *package-name**2**.yml* (https://github.com/openupm/openupm/pull/43/files), then submitted a PR. As a result, the CI failed on the filename verification test.

**Comment by gekidoslair** [comment]
I was the one that changed it, thinking that might be a way to get it moving again - did some digging and found the branches / pull-requests in the fork - all good.

Finally 'get' the whole publish flow now as well so that's a bonus ;}

Thanks for your patience!
