### ISSUE TITLE
Missing package: eu.netherlands3d.webgl-copy-paste

### ISSUE THREAD

**Issue by mvriel** [openupm/openupm#4590]
#### Bug category

- [x] Website: issues related to browse or discover packages.
- [ ] Pipelines: issues related to publish or manage a package.
- [x] Registry: issues related to the registry server.
- [ ] Unity Editor: issues related to how OpenUPM works with the Unity Editor.
- [ ] Documentation
- [ ] Others

#### Steps to reproduce

Go to https://openupm.com/packages/eu.netherlands3d.webgl-copy-paste/ and see a 404, or search for the package on the website and see it is not there.

#### What is expected?

After https://github.com/openupm/openupm/pull/4589 was merged, I expected to find the package at https://openupm.com/packages/eu.netherlands3d.webgl-copy-paste/; but it is not available and the search also doesn't show it.

#### What is actually happening?

It ain't there 😅

**Comment by favoyang** [comment]
Sorry for the delay. It's a build bug https://github.com/openupm/openupm-next/actions/runs/7609890000. I will update you here when it gets resolved.

**Comment by favoyang** [comment]
The issue has been resolved after a rebuild.
