### ISSUE TITLE
UI elements should inherit from Selectable instead of Monobehaviour

### ISSUE THREAD

**Issue by sgoffman** [openupm/openupm#4606]
## Feature request

If UI elements (e.g. ReorderableListElement) inherited from Selectable instead of Monobehaviour then they would be able to take advantage of Unity's built-in OnPointerDown/Up/Leave events. This would give users the options of setting up Transition effects on those elements.

#### Feature category

- [ ] Website: improve the way to browse or discover packages.
- [ ] Pipelines: improve the way to publish or manage a package.
- [ ] Registry: improve the registry server.
- [x] Unity Editor: improve how OpenUPM works with the Unity Editor.
- [ ] Documentation
- [ ] Others

#### What problem does this feature solve?
The current system doesn't allow using Unity's Transitions system for selectables, for e.g. causing them to highlight when pressed.

#### How should this be implemented in your opinion?

Simply changing the parent class of UI elements (e.g. ReorderableListElement) from "Monobehaviour" to "Selectable"

**Comment by favoyang** [comment]
Hi @sgoffman,

Please contact the package owner to get tech support for a specific package.

**Comment by sgoffman** [comment]
Will do, thanks!
