### ISSUE TITLE
Unpublish packages

### ISSUE THREAD

**Issue by uurha** [openupm/openupm#4667]
### Unpublish package request
**What's the reason to unpublish the package entirely?**
This package is unsupported, to avoid any problems for developers who using my collection of plugins, so I want to remove all versions to prevent problems for developers.

**What's the package name?**
com.tdw.betterjoystick
com.tdw.betterlocator
com.tdw.betterservices

**Have you removed the package meta file and added the package name to the blocked-scopes.yml?**
No

**Comment by favoyang** [comment]
Done.
