### ISSUE TITLE
Cant see water in android platform

### ISSUE THREAD

**Issue by PiyushHadiya** [openupm/openupm#4679]
#### Bug category

- [ ] Website: issues related to browse or discover packages.
- [x] Pipelines: issues related to publish or manage a package.
- [ ] Registry: issues related to the registry server.
- [x] Unity Editor: issues related to how OpenUPM works with the Unity Editor.
- [ ] Documentation
- [x] Others

**Comment by PiyushHadiya** [comment]
Not seeing water in Android platform

**Comment by favoyang** [comment]
Hi @PiyushHadiya,

Our platform only hosts open-source packages. For a specific question please get in touch with the package author's repository instead.
