### ISSUE TITLE
Listed package tag/version does not exist and raises errors on install (com.realitycollective.service-framework)

### ISSUE THREAD

**Issue by SimonDarksideJ** [openupm/openupm#4680]
## Bug report
For some reason, the package pull for [com.realitycollective.service-framework](https://openupm.com/packages/com.realitycollective.service-framework) is bad.

It lists the latest version as 1.0.4 which does not exist, as the latest is a pre-release of 1.0.4-pre.3

Ultimately, just odd?

#### Bug category

- [ ] Website: issues related to browse or discover packages.
- [ ] Pipelines: issues related to publish or manage a package.
- [X] Registry: issues related to the registry server.
- [ ] Unity Editor: issues related to how OpenUPM works with the Unity Editor.
- [ ] Documentation
- [ ] Others

#### Steps to reproduce

1. look at the [SF github page tags](https://github.com/realitycollective/com.realitycollective.service-framework/tags), note there is no 1.0.4, only 1.0.4-pre.3 exists
2. Review [com.realitycollective.service-framework](https://openupm.com/packages/com.realitycollective.service-framework) OpenUPM page, it states 1.0.4

#### What is expected?

The correct release of 1.0.4=pre.3 should show

#### What is actually happening?

An invalid version 1.0.4 shows

**Comment by favoyang** [comment]
It is a known issue that our pipeline allows the publishing of a version even when the Git tag does not match the `package.json` version. Refer to https://github.com/openupm/openupm/issues/4483 for details.

For [com.realitycollective.service-framework](https://github.com/realitycollective/com.realitycollective.service-framework):

- The tag [v1.0.4-pre.2](https://github.com/realitycollective/com.realitycollective.service-framework/releases/tag/v1.0.4-pre.2) has a `package.json` version of `1.0.4`, which is a mismatch. It has been published as the "latest" version.
- The tag [v1.0.4-pre.3](https://github.com/realitycollective/com.realitycollective.service-framework/releases/tag/v1.0.4-pre.3) has a `package.json` version of `1.0.4-pre.2`, also a mismatch. According to semantic versioning (semver) rules, a pre-release is always considered less than a formal release (`v1.0.4-pre.2 < 1.0.4`), so the later version will not override the current "latest" tag.

To resolve this, contact the author and request them to bump the version to `1.0.5-pre.x` and then ensure the Git tag version aligns with the `package.json` version. If not addressed, either Unity or `openupm-cli` will by default install the version tagged as "latest".

Reference: https://semvercompare.azurewebsites.net/?version=1.0.4&version=1.0.5-pre.1&version=1.0.4-pre.1&version=1.0.4-pre.2

**Comment by favoyang** [comment]
OpenUPM doesn't override the published version. You can only ask for un-publishing a version for a few restricted reasons https://openupm.com/docs/modifying-upm-package.html 

As said, you need to go for 1.0.5-pre.x to reset the "latest" field.

**Comment by SimonDarksideJ** [comment]
Resolved by forcing update of package, not an ideal solution
