### ISSUE TITLE
Preview of packages that didn't specify a cover image changed

### ISSUE THREAD

**Issue by julienkay** [openupm/openupm#4745]
## Bug report
Previously, when publishing a package and not specifying a cover image, the social media preview of the GitHub repository was used. It seems this isn't the case anymore. If this is intended behaviour feel free to close this ticket. In that case, is it ok to do a PR to update the image for an existing package?

#### Bug category

- [X] Website: issues related to browse or discover packages.
- [X] Pipelines: issues related to publish or manage a package.
- [ ] Registry: issues related to the registry server.
- [ ] Unity Editor: issues related to how OpenUPM works with the Unity Editor.
- [ ] Documentation
- [ ] Others

**Comment by favoyang** [comment]
Yes, we removed the feature of picking the social image as the package preview image.

Please submit a PR to update the image field of your package metadata file located at `data/packages`.
