### ISSUE TITLE
Missing package version

### ISSUE THREAD

**Issue by bdovaz** [openupm/openupm#4790]
This repository has a release (and tag) v.1.0.1:

https://github.com/Cysharp/YetAnotherHttpHandler/releases

But it does not appear in the OpenUPM package:

https://openupm.com/packages/com.cysharp.yetanotherhttphandler/?subPage=versions

I understand that it is an internal problem of OpenUPM and its discovery of new versions?

Thank you.

**Comment by favoyang** [comment]
https://github.com/Cysharp/YetAnotherHttpHandler/blob/d2b632b963375adca70c5d5f0164029ca000926c/src/YetAnotherHttpHandler/package.json

https://openupm.com/packages/com.cysharp.yetanotherhttphandler/?subPage=pipelines

The author creates the 1.0.1 tag before bumping the version.

To fix it:
 - recreate tag 1.0.1 from the main branch
 - or bump the version to 1.0.2 and then create a new tag for it.
