### ISSUE TITLE
Unpublish package request

### ISSUE THREAD

**Issue by uurha** [openupm/openupm#4834]
#### What's the reason to unpublish the package entirely?
This package is unsupported, to avoid any problems for developers who using my collection of plugins, so I want to remove all versions to prevent problems for developers.

#### What's the package name?
com.tdw.better.components

#### Have you removed the package meta file and added the package name to the blocked-scopes.yml?
No

**Comment by favoyang** [comment]
Approved

**Comment by uurha** [comment]
Hi, it's appers that package was not fully unpublished. I tried to clean package manager Unity cache, but it still appears in list.
![image](https://github.com/openupm/openupm/assets/22265817/fa2d9b58-7ac2-4f42-96a3-898e95216a9c)
