### ISSUE TITLE
Unpublish package

### ISSUE THREAD

**Issue by uurha** [openupm/openupm#4845]
#### What's the reason to unpublish the package entirely?
This package is unsupported, to avoid any problems for developers who using my collection of plugins, so I want to remove all versions to prevent problems for developers.

#### What's the package name?
com.tdw.better.locator

#### Have you removed the package meta file and added the package name to the blocked-scopes.yml?
No

**Comment by favoyang** [comment]
```
$ openupm view com.tdw.better.locator
ERR! 404 package not found: com.tdw.better.locator
```
