### ISSUE TITLE
Unpublish package version

### ISSUE THREAD

**Issue by runette** [openupm/openupm#4934]
Please read the guideline for [unpublishing a package version](https://openupm.com/docs/modifying-upm-package.html#modifying-or-deleting-a-published-version) first.

#### What's the reason to unpublish a version?

I p[published a couple of hours ago a new version that included a test file that leaked through from the source that stops projects building. I forgot to test build before publishing - it works in Editor but will not link!

Ideally - I want to keep the version numbers the same as the source

#### What's the package name?

GeoJSON.NET

#### Which version(s) you want to unpublish?

1.2.19

#### Have you removed or replaced the related Git tag(s)?

I have replaced the GIT tag and ideally would like to republish the version - I don't know if that  is possible

**Comment by favoyang** [comment]
Please read the unpublishing guideline to unpublish a version https://openupm.com/docs/modifying-upm-package.html#unpublishing-a-version

Here I quoted acceptable reasons to unpublish a version:

> The version inadvertently leaks security information, such as accidentally committing a private key and publishing it.
> The version contains harmful content that may endanger the developers who install it.
> The version violates our package guidelines.

I would suggest you bump the version to trigger a new version. It's a very trivial way to fix a bug.
