### ISSUE TITLE
Packages Assigned to Different Author Groups Despite Using the Same GitHub Account

### ISSUE THREAD

**Issue by SolarianZ** [openupm/openupm#4937]
#### Bug category

- [ ] Website: issues related to browse or discover packages.
- [ ] Pipelines: issues related to publish or manage a package.
- [x] Registry: issues related to the registry server.
- [ ] Unity Editor: issues related to how OpenUPM works with the Unity Editor.
- [ ] Documentation
- [ ] Others

#### What is actually happening?

I submitted several packages using the same GitHub account. But they were assigned to different author groups.

Is there a way to modify the author information?

![@BHHSNSYM3P{CZNQ%FI1@PP](https://github.com/openupm/openupm/assets/11539008/9a17f399-4b29-4473-aab5-f1cebc5c61f5)
![image](https://github.com/openupm/openupm/assets/11539008/a4ca6e48-4ac8-4e0e-af9a-31456f230b5e)
![image](https://github.com/openupm/openupm/assets/11539008/8a1031ae-1847-4279-b444-9fb7856c5734)

- https://openupm.com/packages/com.greenbamboogames.assetquickaccess/
- https://openupm.com/packages/com.greenbamboogames.assetchecker/

**Comment by favoyang** [comment]
Please update your package.json's author field, then bump version and tag it to trigger a new release.

https://github.com/SolarianZ/UnityAssetQuickAccessTool/blob/main/package.json

```
 "author": {
    "name": "GBG",
    "email": "vdergow@hotmail.com",
    "url": ""
  },
```
