### ISSUE TITLE
E0 unknown error

### ISSUE THREAD

**Issue by Denis535** [openupm/openupm#4939]
```
Git tag	 Version Commit  Build Note 
v1.0.191 1.0.191 03e3470 43840 E0 unknown error
```

https://openupm.com/packages/com.denis535.clean-architecture-game-framework/?subPage=pipelines

**Comment by favoyang** [comment]
Build log: https://dev.azure.com/openupm/openupm/_build/results?buildId=43840&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=b24cf96b-e476-5cd6-97ae-776d6935d22f&l=32

The recent change from the Git Core team caused the issue: https://github.com/git-lfs/git-lfs/issues/5749. It has a larger impact on using Git with LFS in a CI/CD environment.

A temp fix has been applied, and related versions have been rebuilt.
