### ISSUE TITLE
Unpublish package version

### ISSUE THREAD

**Issue by fu-sasa** [openupm/openupm#4971]
Please read the guideline for [unpublishing a package version](https://openupm.com/docs/modifying-upm-package.html#modifying-or-deleting-a-published-version) first.

#### What's the reason to unpublish a version?
This version crashes Unity.

#### What's the package name?
tech.uslog.eauploader

#### Which version(s) you want to unpublish?
v1.4.0

#### Have you removed or replaced the related Git tag(s)?
Yes

**Comment by favoyang** [comment]
Done.

Please bump the version for your next release.
