### ISSUE TITLE
Unpublish com.realitytoolkit.camera

### ISSUE THREAD

**Issue by FejZa** [openupm/openupm#4986]
Please read the guideline for [unpublishing a package](https://openupm.com/docs/modifying-upm-package.html#unpublishing-a-package) first.

#### What's the reason to unpublish the package entirely?

The package was renamed to com.realitytoolkit.player and we DO want to keep that package published. But the Unity package manager still lists com.realitytoolkit.camera as well even though it does not appear on the openupm website.

#### What's the package name?

The name of the package is `com.realitytoolkit.camera`

#### Have you removed the package meta file and added the package name to the blocked-scopes.yml?

Yes, removed meta file.
No, did not add to blocked scopes

**Comment by favoyang** [comment]
Done.

```
$ openupm view com.realitytoolkit.camera
ERR! 404 package not found: com.realitytoolkit.camera
```
