### ISSUE TITLE
Unpublish com.realitytoolkit.sdk

### ISSUE THREAD

**Issue by FejZa** [openupm/openupm#4987]
Please read the guideline for [unpublishing a package](https://openupm.com/docs/modifying-upm-package.html#unpublishing-a-package) first.

#### What's the reason to unpublish the package entirely?

The RealityToolkit was early in development at the time com.realitytoolkit.sdk was published. In the meantime that package got obsolete and is not needed at all anymore. Since there is no active users we do want it unlishet before people actually start using the Reality Toolkit.

#### What's the package name?

``com.realitytoolkit.sdk`

#### Have you removed the package meta file and added the package name to the blocked-scopes.yml?

Yes, removed meta file.
No, did not add to blocked scopes.

**Comment by favoyang** [comment]
Done.

```
openupm view com.realitytoolkit.sdk
ERR! 404 package not found: com.realitytoolkit.sdk
```
