### ISSUE TITLE
Replace com.qriva.monobehaviourtree

### ISSUE THREAD

**Issue by laicasaane** [openupm/openupm#5111]
To replace a published package with another source repository, please provide the below information.

#### What's the package name?

`com.qriva.monobehaviourtree`

#### The reason to replace a published package?

- I accidentally submitted the `master` branch, but it should be the `upm` branch

#### Please provide the new source repository URL on GitHub.

https://github.com/Qriva/MonoBehaviourTree/tree/upm

#### Is the new UPM repository has at least one working Git tag? (Please test it with the Unity Editor)

The tags were made on the `master` branch, would they be usable for the `upm` branch?

**Comment by favoyang** [comment]
OpenUPM pipeline only tracks Git tags. It can locate the path of the package.json to publish from there.

However, the upm branch you mentioned renamed the `Samples` folder to `Samples`. It's not included in any Git tags, OpenUPM will not be able to process it.

In such case, you have to tag the upm branch along with the upm branch as `upm/x.y.z`, then set up the gitTagPrefix field in the OpenUPM meta file to select it.
