### ISSUE TITLE
bug: Package readme not updated with new release

### ISSUE THREAD

**Issue by SimonDarksideJ** [openupm/openupm#5174]
#### Bug category

- [X] Website: issues related to browse or discover packages.
- [ ] Pipelines: issues related to publish or manage a package.
- [ ] Registry: issues related to the registry server.
- [ ] Unity Editor: issues related to how OpenUPM works with the Unity Editor.
- [ ] Documentation
- [ ] Others

#### Steps to reproduce
A new package release is not updating the readme shown on the website, for instance the following package was recently updated and as part of that, the URL's used on some of the hyperlinks have changed:

https://github.com/realitycollective/com.realitycollective.service-framework

#### What is expected?

The Readme should update with a new version of a package

#### What is actually happening?

The Readme is not changing, especially with URL's

**Comment by favoyang** [comment]
The website syncs the README file once per day. It seems to work for me.

https://github.com/realitycollective/com.realitycollective.service-framework/commit/8ec200b19da8218f1fde5bf671ee6c00a94f22d3

The latest changes to README is the URL from `realityCollective.io` to `realityCollective.net`. I manually checked that the README on openupm is using `realityCollective.net`.

**Comment by SimonDarksideJ** [comment]
OK, looks like it has been updated now.  Probably needs documenting somewhere that the package releases and the readme updates are not in SYNC, as until the readme refreshed, it was still showing the old data, even after a new package was released.

Maybe the readme could also do a prompt refresh when a package does?

**Comment by favoyang** [comment]
> Probably needs documenting somewhere that the package releases and the readme updates are not in SYNC

It's in the FAQ: https://openupm.com/docs/faq.html, but perhaps it can be more clear.

> Maybe the readme could also do a prompt refresh when a package does?

It sounds like a reasonable feature.
