### ISSUE TITLE
feature request: filter by supported Unity version

### ISSUE THREAD

**Issue by mob-sakai** [openupm/openupm#53]

**Comment by favoyang** [comment]
@mob-sakai thanks for the feature request. Do you mean that adding a filter on the list page to filter by supported Unity versions?

It's a reasonable request, but it requires to fetch extra information for the list page. The website is building by a static generator, the list page has a very limited data set (name, description, author, hunter) from the yaml files. So I probably need find a good way to fetch extra information first. Interesting issue, but low priority.

**Comment by mob-sakai** [comment]
> Do you mean that adding a filter on the list page to filter by supported Unity versions?

Yes.

**Comment by favoyang** [comment]
Solved.

![image](https://user-images.githubusercontent.com/125390/74226746-166c0600-4cf8-11ea-8d26-752d209b678b.png)

**Comment by mob-sakai** [comment]
:+1:
