### ISSUE TITLE
Package images do not support relative URLs

### ISSUE THREAD

**Issue by jespersmith** [openupm/openupm#532]
I've added a package image with a relative URL to https://openupm.com/packages/com.halodi.halodi-unity-package-creator/

Browsing https://openupm.com/packages/topics/package-management/ it does not show.

**Comment by favoyang** [comment]
Thanks for reporting the issue.

The image field must be a valid URL, the relative URL is not supported yet.

However, you're suggested to set up a [social image](https://help.github.com/en/articles/customizing-your-repositorys-social-media-preview) instead, which has a higher priority than the YAML file's image field. We crawl your README and social image every half hour.

**Comment by favoyang** [comment]
Refs #533, #536.
