### ISSUE TITLE
Unpublish versions v1.4.2 and 1.4.2 of com.draconware-dev.span-extensions.net.unity

### ISSUE THREAD

**Issue by laicasaane** [openupm/openupm#5349]
Please read the guideline for [unpublishing a package version](https://openupm.com/docs/modifying-upm-package.html#modifying-or-deleting-a-published-version) first.

#### What's the reason to unpublish a version?

The version was created by the upstream's author for .NET in general and can't work with Unity. I will republish the version for Unity.

#### What's the package name?

com.draconware-dev.span-extensions.net.unity

#### Which version(s) you want to unpublish?

`v1.4.2`, `1.4.2`

#### Have you removed or replaced the related Git tag(s)?

Yes, I've removed the Git tag.

**Comment by favoyang** [comment]
Approved and done.
