### ISSUE TITLE
Unpublish package version

### ISSUE THREAD

**Issue by Str4tos** [openupm/openupm#5372]
Please read the guideline for [unpublishing a package version](https://openupm.com/docs/modifying-upm-package.html#modifying-or-deleting-a-published-version) first.

#### What's the reason to unpublish a version?
The release of this version 3.9.7 included a critical error that was fixed and the github tag was recreated. 

#### What's the package name?
https://openupm.com/packages/com.cleversolutions.ads.unity

#### Which version(s) you want to unpublish?
3.9.7

#### Have you removed or replaced the related Git tag(s)?
Yes

**Comment by favoyang** [comment]
Done.
