### ISSUE TITLE
shasum check fails for Unity NuGet packages

### ISSUE THREAD

**Issue by mikeskydev** [openupm/openupm#5383]
#### Bug category

- [ ] Website: issues related to browse or discover packages.
- [ ] Pipelines: issues related to publish or manage a package.
- [x] Registry: issues related to the registry server.
- [x] Unity Editor: issues related to how OpenUPM works with the Unity Editor.
- [ ] Documentation
- [ ] Others

#### Steps to reproduce
- Add OpenUPM scoped repository and a scope covered by Unity NuGet (e.g. org.nuget.sharpziplib)
- Install a version of that package (e.g. 1.3.1)

#### What is expected?
- The package installs
#### What is actually happening?
- Error in Unity saying shasum check failed (this is sharpziplib 1.3.1)
```
shasum check failed for %LOCALAPPDATA%\Unity\cache\npm\package.openupm.com\.tmp-26384-S5xEMqf7F8bs\tarball\package.tgz
Expected: af57682bb45c7258a44763e914e9bbc51c30a6e2
Actual:   b634395dba4d369f68f744b10e737fd9f48fe426
...
```
#### Other relevant information
Looking at `%LOCALAPPDATA%\Unity\cache\npm\package.openupm.com\package.openupm.com\org.nuget.sharpziplib\.cache.json ` or https://package.openupm.com/org.nuget.sharpziplib shows the same expected shasum of `af57682bb45c7258a44763e914e9bbc51c30a6e2` for 1.3.1. Manually downloading the tgz and doing shasum locally shows the reported mismatch `b634395dba4d369f68f744b10e737fd9f48fe426`.

Going directly to xoofx's uplink, it has another different shasum (`8eb24cf15b1e684b2f8c5593b90e68c14a6caa97`), but does match the downloaded package so installs successfully.

This happens on multiple packages; we wanted to switch to the OpenUPM versions as Unity NuGet occasionally goes down for hours, whereas OpenUPM uptime is excellent!

**Comment by favoyang** [comment]
Thanks for reporting the issue. A rebuild on the nuget side could result in the same version being inconsistent. I will investigate more.

**Comment by favoyang** [comment]
> Going directly to xoofx's uplink, it has another different shasum (8eb24cf15b1e684b2f8c5593b90e68c14a6caa97), but does match the downloaded package so installs successfully.
```
wget https://package.openupm.com/org.nuget.sharpziplib/-/org.nuget.sharpziplib-1.3.1.tgz
shasum org.nuget.sharpziplib-1.3.1.tgz
8eb24cf15b1e684b2f8c5593b90e68c14a6caa97
```

All `org.nuget.*` package caches have been refreshed.

The registry software still expects the upstream package to be immutable (and it should be). Until this improves, we will have to refresh the cache manually when needed.
