### ISSUE TITLE
Unpublish package version

### ISSUE THREAD

**Issue by laicasaane** [openupm/openupm#5455]
Please read the guideline for [unpublishing a package version](https://openupm.com/docs/modifying-upm-package.html#modifying-or-deleting-a-published-version) first.

#### What's the reason to unpublish a version?

I need to revert a custom fix and synchronize the package with a fix from upstream.

#### What's the package name?

`com.draconware-dev.span-extensions.net.unity`

#### Which version(s) you want to unpublish?

`1.5.1`

#### Have you removed or replaced the related Git tag(s)?

Already removed `upm/1.5.1` tag.

**Comment by favoyang** [comment]
Done.
