### ISSUE TITLE
NuGet packages

### ISSUE THREAD

**Issue by favoyang** [openupm/openupm#553]
Original discussion: https://forum.unity.com/threads/introducing-openupm-upm-registry-with-automatic-build-pipelines.798369/#post-5914997

Nesting DLLs directly into the UPM package is a hacky practice to make a single package just work. But get troubled when two packages included the same DLL. To resolve the conflict, you have to eject (embed) one package manually to the Packages, then remove the DLL. The ideal solution is to have a group of NuGet packages converts to UPM format to allow other packages to reference.

xoofx's UnityNuGet is such a project with limited resources and an automatic approach. These packages are using org.nuget as scope.

https://github.com/worldreaver is also something similar and published to OpenUPM. e.g. https://openupm.com/packages/com.worldreaver.systemmemory/. These packages are using com.worldreaver as scope.

There're other cases like https://openupm.com/packages/jillejr.newtonsoft.json-for-unity/ does for Newtonsoft.Json, by adding more features like custom builds targeting different platforms and link.xml for code stripping.

Notice that though these packages are using their own package namespace, the DLL filenames are the same. So you can only install one of them.

What I may come with is a solution to make it easier to publish NuGet package to OpenUPM.
- It can be something like xoofx does, using an automatic approach. I need more research to see if it can be achieved for adding customization automatically like the newtonsoft.json example above.
- It can be something like worldreaver does use one GitHub repository for one NuGet package, but with a more "official" namespace. This will be less work for OpenUPM to verify those packages and more flexible to add customizations. And we may need to develop a GitHub Action to help track NuGet changes and create PR automatically.

I'm not sure which way to go, probably need some trial-and-error process. When these packages are ready, we can start to promote it to the community, but promoting a good practice may take a long time.

**Comment by bdovaz** [comment]
Any updates @favoyang ??

**Comment by favoyang** [comment]
@bdovaz Nope... haven't got enough time to pick is up.

**Comment by bdovaz** [comment]
Ping! How is this going @favoyang?

I hope you take @xoofx 's approach.

**Comment by favoyang** [comment]
I apologize for the long delay. Our resources are limited. We're currently focusing on the adoption of the [Unity TOS updates](https://forum.unity.com/threads/updates-to-our-terms-of-service-and-new-package-guidelines.999940/). This may happen next year.
