### ISSUE TITLE
Unity Package Manager Error

### ISSUE THREAD

**Issue by iDreamsOfGame** [openupm/openupm#848]
![image](https://user-images.githubusercontent.com/416084/84924414-0ecfca00-b0fb-11ea-9fef-46762e78d72c.png)
When I open project at home. An error alert will show up. My ISP is China Mobile. But when I open the same project in the office (ISP is China Telecom), everything is fine. So I think it's a network issue. PS: using SSR as proxy client to open project can not solve this issue. (Maybe some settings are wrong? Please tell me if you know)

**Comment by timsims** [comment]
I have encountered this problem too. But it only happen on Unity 2019.4.01f LTS,  If I Switch back to 2019.3.15f1 the problem goes away

Someone on Unity fourm [mentioned](https://forum.unity.com/threads/failed-to-resolve-packages-registry-configuration-is-invalid.906443/) private npm server has been banned by Unity China

**Comment by iDreamsOfGame** [comment]
> I have encountered this problem too. But it only happen on Unity 2019.4.01f LTS, If I switch back to 2019.3.15f1 the problem goes away
> 
> Someone on Unity fourm [mentioned](https://forum.unity.com/threads/failed-to-resolve-packages-registry-configuration-is-invalid.906443/) private npm server has been banned by Unity China

So that means if I change the unity editor to global version can solve this issue?

**Comment by favoyang** [comment]
The issue is caused by the network blocking. Perhaps happens a bit randomly between China-US internet tunnel.

The longer-term solution will be a China-specific spin-off. I'm working on it, but it will be a slow process to find a supportive China-local vendor and tweak the architecture to make it easier to set up a spin-off.

Until then you can
- Use an [HTTP proxy](https://docs.unity3d.com/Manual/upm-network.html#Proxy), that's the default way Unity handles network issue. For windows users, you shall [modify the environment](https://docs.oracle.com/en/database/oracle/r-enterprise/1.5.1/oread/creating-and-modifying-environment-variables-on-windows.html#GUID-DD6F9982-60D5-48F6-8270-A27EC53807D0), then restart your laptop. [Privoxy](https://www.privoxy.org/) or [polipo](https://www.irif.fr/~jch/software/polipo/) are common tools to convert SSR/Socks to HTTP proxy.
- Use a VPN with a global set up to redirect all your traffic including DNS query to a remote server.

**Comment by iDreamsOfGame** [comment]
> The issue is caused by the network blocking. Perhaps happens a bit randomly between China-US internet tunnel.
> 
> The longer-term solution will be a China-specific spin-off. I'm working on it, but it will be a slow process to find a supportive China-local vendor and tweak the architecture to make it easier to set up a spin-off.
> 
> Until then you can
> 
> * Use an [HTTP proxy](https://docs.unity3d.com/Manual/upm-network.html#Proxy), that's the default way Unity handles network issue. For windows users, you shall [modify the environment](https://docs.oracle.com/en/database/oracle/r-enterprise/1.5.1/oread/creating-and-modifying-environment-variables-on-windows.html#GUID-DD6F9982-60D5-48F6-8270-A27EC53807D0), then restart your laptop. [Privoxy](https://www.privoxy.org/) or [polipo](https://www.irif.fr/~jch/software/polipo/) are common tools to convert SSR/Socks to HTTP proxy.
> * Use a VPN with a global set up to redirect all your traffic including DNS query to a remote server.

I will try it when I go back home. See if the method that unity manual mentioned is ok. Thanks!

**Comment by timsims** [comment]
I can confirm it's Unity China edition's problem, not network blocking

What I do:
Download UnityDownloadAssistant-2019.4.0f1 from [here](https://github.com/UnityITellYou/UnityITellYou.github.io/releases) and use it to install Unity , everything works fine for me

**Comment by favoyang** [comment]
That's a funny thing then. I know the China-specific version did some optimizations to make Unity services more smooth in China. But I assume that are limited to Unity services. I doubt if it has something to do with the scoped registry, which should be a direct HTTP connection from your computer to the scoped registry. Unless it proxies all HTTP connections to their server, to make your local HTTP proxy settings useless. It's a weird guess though.

**Comment by iDreamsOfGame** [comment]
> That's a funny thing then. I know the China-specific version did some optimizations to make Unity services more smooth in China. But I assume that are limited to Unity services. I doubt if it has something to do with the scoped registry, which should be a direct HTTP connection from your computer to the scoped registry. Unless it proxies all HTTP connections to their server, to make your local HTTP proxy settings useless. It's a weird guess though.

I tried the way that @timsims mentioned. Everything goes fine. No error message alert any more. Seems that there is a firewall behind the China-specific version block something. I tried set environment as Unity manual said. No effect to China-specific version. I think this issue can be closed. Cause this is not a bug, also not a issue we can solve. The most important thing is, DO NOT DOWNLOAD UNITY EDITOR THROUGH UNITY HUB!!!

**Comment by favoyang** [comment]
FYI: the OpenUPM China region is available at https://openupm.cn/

See announcement at [medium](https://medium.com/openupm/openupm-china-region-and-jd-cloud-ai-sponsorship-70ed70d44597) or [zhihu](https://zhuanlan.zhihu.com/p/328401401).
