### ISSUE TITLE
Need to re-submit an existing package with new name

### ISSUE THREAD

**Issue by laicasaane** [openupm/openupm#877]
It's my bad when I submitted [this package](https://github.com/laicasaane/unity-text-typer) with the author identity of the previous fork (which is [redbluegames](https://github.com/redbluegames/unity-text-typer)) rather than my own identity. I also defined the asmdef with their identity too. Seeing that they are updating their fork, I'm afraid there might be a conflict between us if they want to submit their fork to OpenUPM in the future. So I want to change the manifest and asmdef, and the package name of my fork. Breaking changes are unfortunate but this must be done before too late.

**Comment by favoyang** [comment]
Hi @laicasaane,

Thanks for your contribution. You can consider the process as publishing a package, then remove/deprecate the old one.

Here's what you can do:
- update your fork for the new package and asmdef name.
- delete the old[ package YAML file](https://github.com/openupm/openupm/blob/master/data/packages/com.redbluegames.texttyper.yml), you can use the trash icon on the GitHub page to send a PR.
- wait the PR gets merged.
- bump version, then create a new tag.
- submit your new package, set the minimal version to build to your new tag.
- wait the PR gets merged and the pipelines to get the job done.

Then,
- no published packages get removed, it won't break anyone who uses it now.
- the new version is published under the new package name.

**Comment by favoyang** [comment]
closed by #889.
